### ISSUE TITLE
[BUG] Search fails if the words contains "ñ"

### ISSUE THREAD

**Issue by Paco8** [arvvoid/plugin.video.hbogoeu#111]
* [x] Are you running the latest version?

**Describe the bug**
I'm using HBO Spain. I tried to search for a movie using the word "señal", the addon displayed an error message and the search wasn't performed.
It also fails if I enter a word with "ç", so it seems that it fails when using non ASCII characters.

**To Reproduce**
Go to the search option in the addon, type "señal".

**Expected behaviour**
It shouldn't fail and display the search results.

## Debug log
https://pastebin.com/9xLaYCnn

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

It also fails in a nvidia shield.

The log also shows some error messages regarding thumbnails.

**Comment by arvvoid** [comment]
Hello, tnx for reporting. A fix will be available soon. 

The thumbnails errors can be ignored and are expected on some items.

**Comment by arvvoid** [comment]
@Paco8 Please test the current master the issue should be fixed.

**Comment by Paco8** [comment]
Yes, it's working now.
Thank you.

**Comment by arvvoid** [comment]
Ok perfect this is fixed then
