### ISSUE TITLE
[BUG] HBO Nordic subtitles fail to load with SSL error

### ISSUE THREAD

**Issue by Evili84** [arvvoid/plugin.video.hbogoeu#116]
* [x] Are you running the latest version?

**Describe the bug**
I've enforced the subtitle settings from Kodi for English and Finnish subtitles. Subtitles remain grayed out after video starts playing.

**To Reproduce**
Steps to reproduce the behaviour:
Start playing a video
Look for subtitles, nothing there

**Expected behaviour**
Kodi should start automatically using the subtitle that is set for default.

## Debug log
https://paste.kodi.tv/ijubiyarim.kodi
Look for row:
DEBUG: [plugin.video.hbogoeu] Unexpected error in subtitles processing:

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**
Raspberry Pi 4 B+ 4GB
2019-09-26-raspbian-buster
Kodi 18.4 Leia

**Comment by arvvoid** [comment]
Hello, that's most likely a system problem, not an add-on problem. Nothing can be done at the add-on level to fix this. Users in the past reported similar problems with raspbian-buster. Personally don't use it on any of my devices so I can't test directly.

Please try in your system shell `curl https://static.hbonordic.com/1f10ced-0103e8eb7d3/48b883e84ba44d49bbaa53eabd7516cd.xml` and post the output here to confirm is a system problem.

You might look these post might give you some insight: https://forum.kodi.tv/showthread.php?tid=339798&pid=2889249#pid2889249

**Comment by Evili84** [comment]
Ok, thanks for the info. 

I suspected something like that. Might just be something wrong with raspbian root CA. In case I find something usefull I'll update it here.

**Comment by Evili84** [comment]
This error seems to be related to OpenSSL, version which I have installed is 1.1.1d, and apparently it does have some problems.

If anyone has this problem the solution that worked for me can be found from here https://stackoverflow.com/a/58531438
