### ISSUE TITLE
No "Kids" category

### ISSUE THREAD

**Issue by artemplaksiy** [arvvoid/plugin.video.hbogoeu#126]
* [x] Are you running the latest version?

**Describe the bug**
Since today (7.03.2020) the "Kids" category has disappeared from home page. KIDS item is checked in Add-on settings -> Home Category settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the plugin
2. Kids are missing :) 

**Expected behaviour**
The Kids category is displayed in the home page

## Debug log
[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/4302489/kodi.log)

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**
Kodi (18.2 Git:newclock5_18.2-Leia). Platform: Linux ARM 32-bit
Raspberry Pi3B+

**Additional context**
Czech subscription

**Comment by arvvoid** [comment]
Hello, they removed the legacy Kids category from the API. The new one hasn't been figured out yet, so there is no quick solution for this. I haven't analyzed this properly yet so not sure how much work it will be right now.  Atm I have very little free time so this will take some time to be added probably.
Ofc like always if someone has time to work on this right away pull requests are welcome.

**Comment by artemplaksiy** [comment]
I thought so, thanks for confirmation. I'm already downloading Pycharm :muscle:

**Comment by arvvoid** [comment]
related to #12

**Comment by arvvoid** [comment]
@artemplaksiy Good news after a lot of frustration and after almost giving up found a way... please test the current master if no problems are found in new and existing functionality I will make a release soon: https://github.com/arvvoid/plugin.video.hbogoeu/archive/master.zip

**Comment by artemplaksiy** [comment]
Well done! Thank you very much! My son is going to perform a stress test here :laughing:

**Comment by durip** [comment]
Hi @arvvoid, great work. I made test with current master and Kids category is working. Searching is also working well. Thanks. Operator: skylink Slovakia

**Comment by artemplaksiy** [comment]
@arvvoid, Kids category works without issues. Thanks again for great support and quick fix! Ready for release for me :+1:
