### ISSUE TITLE
No Kids results in search

### ISSUE THREAD

**Issue by artemplaksiy** [arvvoid/plugin.video.hbogoeu#127]
* [x] Are you running the latest version?
v2.3.10

**Describe the bug**
Search doesn't return all items available on HBO

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Search'
2. Enter 'paw'
3. Press OK
4. Only one item is displayed in search result: PANIC ATTACK (writer: **Paw**eł Maślona) 

**Expected behaviour**
Currently there are two matches available in HBO library:
- **Paw** patrol
- PANIC ATTACK (writer: **Paw**eł Maślona) 

## Debug log
[search_kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/4333189/search_kodi.log)

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**

Kodi (18.2 Git:newclock5_18.2-Leia). Platform: Linux ARM 32-bit
Using Release Kodi x32 build (version for Raspberry Pi)
Kodi compiled 2019-05-04 by GCC 8.2.0 for Linux ARM 32-bit version 4.19.36 (267044)
Running on LibreELEC (official): 9.0.2, kernel: Linux ARM 32-bit version 4.19.36

**Comment by artemplaksiy** [comment]
After a quick investigation: current URL for searching is:
2020-03-14 16:18:10.367 T:1552429936   DEBUG: [plugin.video.hbogoeu] GET FROM HBO URL: https://czapi.hbogo.eu/v8/Search/Json/ENG/COMP/paw/0

, but in web browser I see this URL:
https://czapi.hbogo.eu/v8/Search/json/CES/COMP/paw/-/-/-/-/-/3

See how searching working in this logs:
[browser_search.har.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4333211/browser_search.har.zip)
[plugin_search.har.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4333212/plugin_search.har.zip)

I already changed the URL in my forked branch and after quick test search works fine..

**Comment by artemplaksiy** [comment]
After a little bit longer investigation :smile: I assumed that the current search doesn't find any **series** and only in Kids category. For example, I can find "Bad Banks" but cannot find Paw patrol, Blaze and the Monster Machines or Slugterra.
My change above at first glance fix this problem, but I'm still not sure about the pull request.

**Comment by arvvoid** [comment]
Hello, your findings are correct. Made the necessary change to the search URL. After some testing will be included in the next release is already in master.

**Comment by arvvoid** [comment]
@all-contributors please add @artemplaksiy for bug, ideas

**Comment by arvvoid** [comment]
Test release: https://github.com/arvvoid/plugin.video.hbogoeu/releases/tag/2.3.11

Testing on Matrix is not necessary atm since lot of dependencies are still missing. Test only on Leia.

**Comment by artemplaksiy** [comment]
Great! I'll be happy to test it! :+1:

**Comment by arvvoid** [comment]
@artemplaksiy see also #126 you can test directly the current master there have been a breakthrough last night regarding the Kids category :)

**Comment by artemplaksiy** [comment]
Search is working properly now. Attaching the log: [test_kodi.log.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/4337510/test_kodi.log.zip)

There are few findings:
- HBO API doesn't support searching only by one character, but plug-in is trying to do it and got then an Inernal Server Terror :laughing: See: 2020-03-16 09:45:38.148 in the log. Funny note: HBO informs in the web browser, that user need to enter minimum 3 characters to search, but the API allows to use two characters and return the result.
- In cases when search result contains a large number of items the plug-in (from user point of view) is going to stuck. See time 2020-03-16 09:45:56.514 in attached log. HBO returns a wild 554Kb json with 8133 rows :open_mouth: The plug-in then going to collect data for displaying, but it's took too much time.

However, all this issues apparently are not relevant to this bug, so I think we can close it and release the fix.

**Comment by arvvoid** [comment]
Tnx for reporting will look into those issues and try to polish the rough edges :) What search string returned such a large result? I should probably limit the search to 50 results more is not going to be useful anyway...

**Comment by artemplaksiy** [comment]
This one: https://czapi.hbogo.eu/v8/Search/Json/ENG/COMP/pa/-/-/-/-/-/3
I know, there are only two chars which shouldn't be used, but yesterday it was stuck with four also ("thro" for example). It's worth to point that after several attempts plug-in successfully displaying the results.. maybe a cache helping.

**Comment by arvvoid** [comment]
Yes, it's the cache helping the add-on cache all requests with 24h validity so no request is repeated more than once every 24h to HBO go. But such large result will generate a lot of additional requests to hbo go with the current code, to get additional content info like plot ecc... so i suggest not testing that again until fixed to avoid spikes in requests and potential trouble.
I will limit the search result and implement the 3 char min requirement before release probably later today. Tnx for letting me know.

**Comment by arvvoid** [comment]
Is fixed now is already in master will make a release later today.
Now it won't send searches below 3 chars, it limit to 20 results at API level and i also implemented a hard 20 result limit client side.
