### ISSUE TITLE
[BUG] Wrong language codes?

### ISSUE THREAD

**Issue by dagwieers** [arvvoid/plugin.video.hbogoeu#129]
**Describe the bug**
While looking over the translations of your add-on, I noticed that some of the language codes used in *resources/language/* are incorrect.

- Czech &rarr; **cs_cz**
- Swedish &rarr; **sv_se**

**Comment by dagwieers** [comment]
We are starting an initiative to unite Kodi translators so more add-ons can get widely translated.
You can add your add-on to the wiki at: https://github.com/kodi-addons/translators/wiki/Addons

**Comment by arvvoid** [comment]
@dagwieers Thank you, missed that, and nobody complained about not working translation. Will correct those and recheck the rest tonight.

**Comment by arvvoid** [comment]
@all-contributors please add @dagwieers for bug, ideas
