### ISSUE TITLE
Memory Error importing import defusedxml.ElementTree

### ISSUE THREAD

**Issue by orangutanoide** [arvvoid/plugin.video.hbogoeu#135]
* [X ] Are you running the latest version?
Yes, 2.4.1

**Describe the bug**
Addon does not start. 

[paste kodi log file](https://paste.kodi.tv/nidujuheja.kodi)

There is a "Memory Error" importing defusedxml.ElementTree at hbogolib/handlersp.py

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**
This is a retropie distribution on a raspberry pi , with kodi installed from the official repository (Kodi version 18.2).
Since is seems to be a memory problem, I tried to increase the swap size. It made no difference.

The ImputStream Helper information shows:

Kodi version: 18.2
Kodi platform/architecture: Linux/arm (this is a raspberry)
InputStream Helper version: 0.4.4
InputStream Adaptive version: 2.3.17
Widevine version: 4.10.1610.6
Chrome OS version: 17739.94.0

**Comment by arvvoid** [comment]
Hello, sorry but nothing I can do about that if the device don't have enough memory to load a dependency.

**Comment by arvvoid** [comment]
Also, Kodi is at 18.6 now so maybe try the latest release, the problem doesn't happen on any of my rpi devices, I regularly use, have plenty of memory left, so something is taking up your memory but that is out the scope of the add-on.

**Comment by arvvoid** [comment]
You can try this branch with dropped defusedxml to compare performance and report back: https://github.com/arvvoid/plugin.video.hbogoeu/archive/no_defused_xml.zip

Since this is a client the security impact won't be much if plain versions are used but have to evaluate if merge this in main or not.
