### ISSUE TITLE
[BUG] Telekom Romania fail setup (affects some other operators as well)

### ISSUE THREAD

**Issue by Buraddo23** [arvvoid/plugin.video.hbogoeu#140]
* [x] Are you running the latest version?

**Describe the bug**
Login attempt returns Error 403 even with correct credentials, possibly a different endpoint than other operators.

**To Reproduce**
Run setup, fails to connect.

**Expected behaviour**
Login succesful.

## Debug log

[https://paste.kodi.tv/opujeyevex.kodi](https://paste.kodi.tv/opujeyevex.kodi)

**Operating System**

* [x] Linux (ARM)
* [x] Windows (x86/x64)

**Comment by arvvoid** [comment]
@Buraddo23 tnx for reporting, this reveled a change on a larger scale there are more operators like this added recently. Published here https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Regional-support a complete operators list the ones marked as DIRECT AFFILIATE are the ones affected by this issue.

Please test the fix here https://github.com/arvvoid/plugin.video.hbogoeu/archive/fix_affiliate_operators_direct_endpoint.zip and let me know and I will merge and push to the Kodi add-on repo as soon as possible.
More testers from more operators/countries welcome.

**Comment by arvvoid** [comment]
Affected operators and addressed in the fix:

Bulgaria
* DIRECT AFFILIATE: Telekabel
* DIRECT AFFILIATE: NET1

Czech Republic
* DIRECT AFFILIATE: Vodafone Česká republika
* DIRECT AFFILIATE: Skylink CZ from 1.4.2020
* DIRECT AFFILIATE: UPC TV (from 1.4.2020)

Montenegro
* DIRECT AFFILIATE: MTEL

Romania
* DIRECT AFFILIATE: Telekom Romania

Serbia
* DIRECT AFFILIATE: Test RS 1
* DIRECT AFFILIATE: Supernova

Slovakia
* DIRECT AFFILIATE: Skylink SK from 1.4.2020

Portugal
* Vodafone TV
* Vodafone Móvel

**Comment by Buraddo23** [comment]
Tested and works as intended

**Comment by arvvoid** [comment]
https://github.com/arvvoid/plugin.video.hbogoeu/pull/141

**Comment by competer982** [comment]
Hi,
I also see this problem with Hungarian UPC Direct, however it says it is AFFILIATE: UPC Direct
Will this fix work for that as well? 
Thanks and BR

**Comment by arvvoid** [comment]
@competer982 Hello, that can't be related to this issue just checked and UPC direct do normal affiliate gateway login, which is stable and not changed for a long time, so please open a separate issue with description and full debug log in your case is not an add-on issue most likely. But only a full debug log can tell more.

**Comment by competer982** [comment]
Hi,
Thanks it was not related, simply UPC was merged into Vodafone, so now we need to use Vodafone as a provider. (I mistakenly choose UPC Direct, but that is some separate).

**Comment by arvvoid** [comment]
@all-contributors please add @Buraddo23 for bug

**Comment by arvvoid** [comment]
The fix is merged in master now, a release will follow soon, will leave this open until it is in the Kodi add-on repository so someone experiencing the same issue can find info easy.

**Comment by arvvoid** [comment]
The version containing the fix is in the kodi add-on repository now for both leia and matrix. Closing.
