### ISSUE TITLE
[BUG] Failed playbayck error

### ISSUE THREAD

**Issue by gbelovai** [arvvoid/plugin.video.hbogoeu#148]
Hi! I wrote on the kodi forum about the playback issue. On the 2.5.5 I'm getting "Failed playback" error messages on every video. (it is a new problem since the 2.5.5 update, on my other device the 2.3.9 version works fine)

full debug: https://paste.kodi.tv/ipowocayod.kodi
inputstream screenshot:
![inputstream](https://user-images.githubusercontent.com/63640826/79212654-3333cf80-7e48-11ea-9880-f40104720bed.JPG)

**Comment by arvvoid** [comment]
Hello @gbelovai it looks like you are affected by this bug as well #146, please help test the fix in pull request #147 and let me know if that fixes the issue

**Comment by arvvoid** [comment]
Fixed in #147

**Comment by arvvoid** [comment]
@all-contributors please add @gbelovai for bug
