### ISSUE TITLE
[BUG] Name HGO

### ISSUE THREAD

**Issue by bluboyo** [arvvoid/plugin.video.hbogoeu#166]
* [ ] Are you running the latest version?
Yes. And kodi 18.8
**Describe the bug**
The name in kodi is HGO not HBO
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

## Debug log - https://kodi.wiki/view/Log_file/Easy

[First of all thanks for making the effort to report an issue, reporting issues is critical to improve the project quality]
[Please include a link to your full debug log. Follow these instructions https://kodi.wiki/view/Log_file/Easy]

[Please note, bug reports without full logs will be marked as ignored rules and ignored untill a log is provided]

**Screenshots**

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Additional context**

**Comment by arvvoid** [comment]
Hello, this is not a bug and not an error. The name is intentional. HBO is a registered trademark.
