### ISSUE TITLE
[SUPPORT] ERROR: [script.module.inputstreamhelper] [u'ldd', u'/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd failed.

### ISSUE THREAD

**Issue by NH3CL** [arvvoid/plugin.video.hbogoeu#173]
* [x] Are you running the latest version?
Yes. 2.6.1

**Describe the bug**
I cannot play anything since the last OSMC update.

**To Reproduce**
Steps to reproduce the behaviour:
1. Search a movie
2. Click on play

**Expected behaviour**
Play the selected moviw

## Debug log - https://kodi.wiki/view/Log_file/Easy

https://pastebin.com/HNJ25Z8h

**Screenshots**
No Screenshots needed

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**

Raspberry Pi 3 B+
Kodi 18.9
InputStream Helper 0.5.1
InputStream Adaptive 2.4.6
Widevine CDM 4.10.1679.0
Chrome OS Expresso 13505.63.0

**Comment by NH3CL** [comment]
Ok, how can i dop this valid?

**Comment by arvvoid** [comment]
Hello, this does not seem like an add-on problem. Looks like you are missing widevine from your installation, the error does not happen within the add-on.
Partial logs are not generally accepted for support, please post full logs in the future. Try reinstalling widevine on your device. If the problem persists you will have to report this on osmc and/or inputstream adaptive, nothing I can do on the add-on side.

From your log:
```
2020-12-13 12:34:24.553 T:1018147040   ERROR: [script.module.inputstreamhelper] [u'ldd', u'/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2020-12-13 12:34:24.554 T:1018147040   DEBUG: [script.module.inputstreamhelper] [u'ldd', u'/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd output:
```
```
2020-12-13 12:34:27.707 T:956281056   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
2020-12-13 12:34:27.711 T:956281056   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)
2020-12-13 12:34:27.711 T:956281056   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
```

**Comment by NH3CL** [comment]
Fixed based on this:
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/411

Restore Widevine to previous version.

**Comment by arvvoid** [comment]
Tnx, going to pin this for a few days since is fresh and other might experience the same issue.

**Comment by mickeelm** [comment]
I dunno if you want more comments or just emoji reactions, but I'm experiencing the same (with all my addons relying on InputStreamHelper)

*EDIT:* Solved by removing `.kodi/cdm` and manually updating InputStreamHelper to 0.5.2. No idea if I had to delete that folder or not but now it works.

**Comment by NH3CL** [comment]
> 
> 
> I dunno if you want more comments or just emoji reactions, but I'm experiencing the same (with all my addons relying on InputStreamHelper)
> 
> _EDIT:_ Solved by removing `.kodi/cdm` and manually updating InputStreamHelper to 0.5.2. No idea if I had to delete that folder or not but now it works.

You just have to go into Addons -> Select InputStreamHelper, and in the Options menu you have to select "Restore Widevin" and choose an older version.
