### ISSUE TITLE
[SUPPORT] Videos not starting anymore after updating Widevine

### ISSUE THREAD

**Issue by sorin-pop** [arvvoid/plugin.video.hbogoeu#174]
* [ ] Are you running the latest version?
Yes

Yesterday, when opening a film in the Netflix addon I got the Widevine update popup, and (foolish me) I chose to install it. After the installation was done my film started and played fine. However, since then , no other film starts up, neither in Netflix nor in this addon.  Does anybody else experience this? Can this be fixed please?

I'm on Kodi Leia on Libreelec on RAspberry Pi.
Thank you.

**Comment by arvvoid** [comment]
Hello, without a log i cant be sure what the problem might be. Most likely connected to this: #173 take a look at the linked solution in that issue.

**Comment by sorin-pop** [comment]
I was not able to get the logs, but yes, I am probably experiencing the issue you refer to. Ultimately it seems that it is a problem with the InputSTream Helper addon, which is responsible for updating Widevine, and apparently (due to a bug, a lack of attention), it downloaded and installed a wrong Widevine, which does not work. (apparently now they quickly realized the mistake and made some new release, although it's not clear how and if this will fix the problem)

Anyhow, the conclusion is that the problem is in the InputSTream Helper, not here. Thank you for your assistance. I am closing this ticket.

**Comment by sorin-pop** [comment]
EDIT: Solved by removing .kodi/cdm and manually updating InputStreamHelper to 0.5.2
