### ISSUE TITLE
Episode and season plot missing

### ISSUE THREAD

**Issue by sile70000** [arvvoid/plugin.video.hbogoeu#18]
Can you consider changing  hbogolib/handlereu.py to something like this?

	Line 1195:             plot = title['Abstract'].encode('utf-8', 'ignore')
	Line 1196:             if 'Description' in title:
	Line 1197:                 if title['Description'] is not None:
	Line 1198:                    plot = title['Description'].encode('utf-8', 'ignore')	
	
	...
	
	Line 1235:         plot = item['Abstract'].encode('utf-8', 'ignore')
	Line 1236:         if 'Description' in item:
	Line 1237:             if item['Description'] is not None:
	Line 1238:                 plot = item['Description'].encode('utf-8', 'ignore')
	Line 1239: 		liz.setInfo(type="Video", infoLabels={"mediatype": media_type, "season": item['Tracking']['SeasonNumber'],
	Line 1240:                                               "tvshowtitle": item['Tracking']['ShowName'],
	Line 1241:                                               "title": item['Name'].encode('utf-8', 'ignore'),
	Line 1242:                                               "Plot": plot})
Thanks.

**Comment by arvvoid** [comment]
@sile70000 tnx for reporting and contributing.  I will try and include your proposed changes.

**Comment by arvvoid** [comment]
included in the last release 2.0.8 beta 22

**Comment by arvvoid** [comment]
@all-contributors please add @sile70000 for bug, ideas
