### ISSUE TITLE
[REQUEST] Integration of MindigTV Go (hu)?

### ISSUE THREAD

**Issue by Zoli1972** [arvvoid/plugin.video.hbogoeu#185]
* [ ] Are you running the latest version?

**Is your feature request related to a problem? Please describe.**
Service MindigTV Go (hu) is yet missing in this addon.

**Describe the solution you'd like**
I'd like to ligin / use MindigTV Go (hu) service registration (NOT MindigTV Extra (hu) ) with this addon.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by arvvoid** [comment]
Hello @Zoli1972 , this add-on supports all operators that are listed on the official hbogo.hu or official client. It pull operators directly from the api. If an operator is available on the hbo go service should be available in the add-on as well. I don't see MindigTV Go in that list. https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Regional-support. There is no MindigTV Go offered as selection on https://hbogo.hu

I'm not familiar with the mentioned service but from googling it, it looks like a complete different service with it's own api that have nothing to do with the hbo go service. It have its own separate website and it own separate app. So inclusion in this add-on would make no much sense. That's a candidate for a separate and dedicated add-on. Personally I'm not interested in developing one.
