### ISSUE TITLE
[SUPPORT] Addon not working anymore [temp problem, provider service down]

### ISSUE THREAD

**Issue by sorin-pop** [arvvoid/plugin.video.hbogoeu#187]
* [ x] Are you running the latest version?

**Befor sending the support request this resources can be checked:**

[Kodi Forum thread](https://forum.kodi.tv/showthread.php?tid=339798) |
[Project wiki](https://github.com/arvvoid/plugin.video.hbogoeu/wiki) | 
[FAQ](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/FAQ) | 
[Troubleshoot](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Troubleshoot)

* [ ] I have already checked all resources above

* [x ] I just want to provide feedback or get in touch

**Please enter your question or feedback**
Yesterday the addon was working fine, I was watching movies. Today, without any change apparently, when I open the addon, nothing happens and it hangs indefinitely, without any error message. The situation can be escaped with the back button (two times).

Does anybody else experience this problem suddenly? (since around today)

Thanks.

**Comment by aovarisofi** [comment]
I think the service is down. I can't login using the browser on a desktop, so it's highly possible that the source of the problem is not the plugin.

**Comment by aovari** [comment]
I think the service is down. I can't login using the browser on a desktop, so it's highly possible that the source of the problem is not the plugin.
Update: it's confirmed on the local official facebook page that they're facing some technical issues.

**Comment by arvvoid** [comment]
Yes, the login on the hbo go website is not working as well, once that is restored all should work fine.

**Comment by arvvoid** [comment]
It started working, all should be fine now :)

**Comment by sorin-pop** [comment]
Yes, it now works. Thank you!
