### ISSUE TITLE
[SUPPORT] Error On Start /Bulgarian HBO/

### ISSUE THREAD

**Issue by pristis** [arvvoid/plugin.video.hbogoeu#19]
Hello!

When I start HBO GO, I receive HBO GO EU error message to check the log.
On first start I select my region /Bulgaria/ and now I can't use it because of error. You can check the log on: https://pastebin.com/XZmGDw0p

Please, help me if you can.

Best regards,
Martin

**Comment by arvvoid** [comment]
@pristis Hello. From the log i see you missing a dependency Cryptodomex. In the early versions of the add-on it was not used. But now is required.
This is not really an issue with the add-on but with the platform its running on. 
Usually it’s present by default, or get auto installed as a script add-on in Kodi on most platforms.

Are you using osmc? Try to install the dependency manually from the shell:

```
sudo apt install python-pip
sudo pip install pycryptodomex
```

I will add gracefull fail and a nicer and informative error message if this dependency is missing.

**Comment by pristis** [comment]
Thanks for the quick answer!

I am using KODI on standalone Raspbian installation, and maybe some packages are not installed, like when use it with osmc for example. 

Yes, pycryptodomex was missed and now it's installed. Also HBO wants me to install Widevine CDM automatically, and after that told me that I must install manually libnss3.

Now everything works great!

Thanks for the support and have a nice day/evening!

Best regards,
Martin
