### ISSUE TITLE
HGO no loger work with Kodi 19

### ISSUE THREAD

**Issue by krokodylowy** [arvvoid/plugin.video.hbogoeu#190]
HI
Android TV unexpectedly upgraded Kodi to 19 and HGO goes away.
HGO or plugins used by 19 are not compatibile with Python 3.

**Comment by arvvoid** [comment]
Hello,

The add-on is fully compatible with Kodi 19 and have been for a long time. If you just updated, the add-ons have to be updated to the matrix version from official repository, it shoud happen automatically. If not the update can be started manually.

If you still experiencing problems please post a full debug log.

**Comment by Dan23R** [comment]
Hello,
Recently, I have on my Kodi 18.9 the following error message on hGO Eu : Communication error, returned Status: 403. I have HBO Go account and until now there were no problems using it  ! Any suggestion for solving the problem ?

**Comment by arvvoid** [comment]
@Dan23R Hello, this is not relevant to this issue. Most likely there is a problem with your credentials, try first to login on the official hbo go website. Some operators changed the login method and some changed from username/password to email/password for login. When you can successfully login on the official website, reset the setup in the addon (config -> Logout (reset setup) and repeat the setup. See https://forum.kodi.tv/showthread.php?tid=339798&pid=3018010#pid3018010 . If you require further assistance please open a propper separate issue following all the rules with a full debug log.

**Comment by arvvoid** [comment]
There is no log and no new info regarding the originally reported issue so closing this. The add-on is fully Kodi 19 and Python3 compatible (Kodi 19 Matrix version of the add-on has to be installed on Kodi 19 for things to work ofc, available in the integrated Kodi add-on repository), there are no other reports of an issue on Kodi 19 so far, and no issues in tests. 

**A new propper issue following all the rules can be opened if the original reporter still experiences a problem.**

If others experience issues on Kodi 19 a propper issue following all the rules and logs can be opened.

**Comment by krokodylowy** [comment]
First HGO installation after new Kodi 19 instalation not worked due notcompatibile third party modules but now after several updates of Kodi modules everything works fine.

Closed
