### ISSUE TITLE
Trying to play any video shows a popup telling user to update the extension.

### ISSUE THREAD

**Issue by tylnesh** [arvvoid/plugin.video.hbogoeu#196]
While already being on the latest version (2.7.1)

**Comment by beasiteri** [comment]
I receive the same error message. Cannot play anything since the 2.7.1 update. OS: LibreELEC 9.2.6 (KODI 18.9.0) - running on Raspberry Pi 4 Model B (Cortex-A72 (ARM v8), 4GB RAM).

**Comment by arvvoid** [comment]
Hello, unfortunately you didn't provide any logs so can't really tell what's going on. Everything works fine for me. Please follow the provided template when reporting an issue.

If you are on rpi (arm/linux) most likely this has nothing to do with this add-on but a new version of widevine is required for playback (old widevine versions can't work anymore with any add-on/app) but new versions of widevine on arm/linux require an os update to work (additional libraries are needed), look here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/437 if you are on libreelec update: https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/ a fix for all distributions might not be available right now, but sooner or later all should catch up. Other platforms like Android, Windows, MacOS should be fine.

If the problem persists after the update please provide full logs.

**Comment by razorxster** [comment]
Hi guys,

I have the same error. I have a hungarian error message (attached).
Summary of the message: New version of the application is reacheable. Please upgade for the nevest version and enjoy the best series and movies.

2.7.1 is installed, but i tried reinstall sometimes. Didn't helped.

I have PPI3 and OSMC 2020.11-1

![IMG_20210610_180753_1](https://user-images.githubusercontent.com/65629377/121559850-4247ea80-ca17-11eb-8dfb-4f1cc8e7b368.jpg)

Thanks in advance!

**Comment by arvvoid** [comment]
Hello, without a full debug log i can't tell or do anything more. 
That message come as an error message from the hbo go api is not internal to the add-on.

It can be an api change on their side as well but everything still work in my region.

It might also just be a temporary error on their side like in this issue: https://github.com/arvvoid/plugin.video.hbogoeu/issues/194

**Impossible to tell without a full log. Follow instructions in readme or issue template to post a proper log.**

**Comment by ArturSierzant** [comment]
Hello,
I have the same problem since yesterday. First it appeared when I was using plugin hbogopl. Then I started to search solution and I found hbogoeu (2.7.1). I installed it hoping it would fix problem, but unfortunately it didn't. I've done some investigation and found this in `kodi.log`:
```
2021-06-10 21:20:14.503 T:1366261984   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogoeu/?mode=2&name=MARE%20OF%20EASTTOWN%20(2021)&url=https%3a%2f%2fplapi.hbogo.eu%2fv8%2fContent%2fjson%2fPOL%2fANMO%2f05175312-18dc-fc7e-b871-94e04d455083%2f
2021-06-10 21:20:14.506 T:1874341904   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogoeu/?mode=2&name=MARE%20OF%20EASTTOWN%20(2021)&url=https%3a%2f%2fplapi.hbogo.eu%2fv8%2fContent%2fjson%2fPOL%2fANMO%2f05175312-18dc-fc7e-b871-94e04d455083%2f) failed
```
This is written to log when I try to open the list of seasons of any series, like: `series -> crime, thrillers -> Mare of Easttown`. For me it looks like HBO changed their api.

Hope that helps in a way.

Regards
Artur

**Comment by arvvoid** [comment]
Hello, this is not helpful full uncut debug logs only tnx

**Comment by razorxster** [comment]
```
2021-06-10 17:58:51.651 T:1764753632  NOTICE: LoadJpeg: unable to load /home/osmc/.kodi/addons/plugin.video.hbogoeu/resources/fanart.jpg
2021-06-10 18:04:55.152 T:1499980000  NOTICE: ADDON: plugin.video.hbogoeu v2.7.1 installed
2021-06-10 18:06:07.367 T:1499980000  NOTICE: ADDON: plugin.video.hbogoeu v2.7.1 installed
2021-06-10 18:06:40.037 T:1678754016   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogoeu/?exclude&mode=13&name=Keres%c3%a9s...&url=INTERNAL_SEARCH
2021-06-10 18:06:40.042 T:1915712432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogoeu/?exclude&mode=13&name=Keres%c3%a9s...&url=INTERNAL_SEARCH) failed
2021-06-10 18:06:52.833 T:1764753632   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for https://www.hbo-europe.com/images/hbo_eu_logo.png
2021-06-10 18:08:48.173 T:1678754016   ERROR: GetDirectory - Error getting plugin://plugin.video.hbogoeu/?mode=2&name=30%20MONEDAS%20(AKA.%2030%20COINS)%20(2020)&url=https%3a%2f%2fhuapi.hbogo.eu%2fv8%2fContent%2fjson%2fHUN%2fANMO%2fe668c7fc-016e-2f4a-08db-881eacc26df9%2f
2021-06-10 18:08:48.175 T:1915712432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogoeu/?mode=2&name=30%20MONEDAS%20(AKA.%2030%20COINS)%20(2020)&url=https%3a%2f%2fhuapi.hbogo.eu%2fv8%2fContent%2fjson%2fHUN%2fANMO%2fe668c7fc-016e-2f4a-08db-881eacc26df9%2f) failed
```


Looks like `https://www.hbo-europe.com` is not reacheable. Maybe is the conent moved fto an other domain, or something other error.

```
root@osmc:/home/osmc/.kodi/temp# nslookup www.hbo-europe.com
Server:         8.8.4.4
Address:        8.8.4.4#53

** server can't find www.hbo-europe.com: NXDOMAIN
```

**Comment by arvvoid** [comment]
That would not cause above mentioned errors, that domain is not really important for the functioning of the add-on. Like I already said 3 times and this is the last time I need a full uncut debug log.

**Comment by razorxster** [comment]
Full kodi log attached.

[kodi.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/6634454/kodi.log)

**Comment by arvvoid** [comment]
Tnx but thats not a debug log

`2021-06-10 12:27:46.827 T:1915712432  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"`

as per instructions in readme enable debug logging a make a full log recreating the issue in question and then post the log.

FROM README:

If you are reporting an issue or asking for support you can go to the ISSUES section.

Please use the provided templates and provide all asked information, including [full kodi debug logs](https://kodi.wiki/view/Log_file/Easy) otherwise its hard or impossible to help or identify and fix the problem.

https://kodi.wiki/view/Log_file/Easy

**Comment by razorxster** [comment]
Debug mode on. Relevant log entries between ~130 and EOF.

[kodi2.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/6634647/kodi2.log)

**Comment by arvvoid** [comment]
Seams a workaround the add-on was using to get the tv shows and movies menu item is no longer valid will have to change method to get those.

Try this as a workaround until an update is ready: try to find the same show using the search function most likely it will work normally (try and please report back if it work), you can add the show to my list and access it and play from there it should work (try and report back), you can find the show through the home various lists those should work fine.
The continue watching section should work fine as well.

PS. only full uncut logs in the future, partial logs may omit important details. Partial logs are not accepted in bug reports.

**Comment by razorxster** [comment]
Hi,

the workaround is wokring, i can watch TV shows, when is search directly. I'm waiting the update.

Thanks a lot!

**Comment by ArturSierzant** [comment]
Hello,

I can also confirm - the workaround is working: both through searching, adding to my list and continue watching.

Many thanks for this.

And of course full log in the future :)

Regards
Artur

**Comment by arvvoid** [comment]
Hello @tylnesh @beasiteri @ArturSierzant @razorxster, a fix is ready but needs user testing before i publish it.

All information is on the pull request: https://github.com/arvvoid/plugin.video.hbogoeu/pull/197

As soon as this is tested in a few regions can be released.

[Note for testers: this affect the EU region, Spain/Nordic is not affected by this issue or changes]

**Comment by arvvoid** [comment]
The fix has been merged in master. There will be a release soon.
