### ISSUE TITLE
[BUG] Error in popup: "The new version of the application is now available. Please update it to continue viewing"

### ISSUE THREAD

**Issue by kkraszy** [arvvoid/plugin.video.hbogoeu#199]
Latest version Addon

**Describe the bug**
Error in popup: "The new version of the application is now available. Please update it to continue viewing"

**To Reproduce**
1. Go to HGO Addon -> Series -> Popular series -> Choose any series
2. See error

## Debug log
2021-08-03 20:10:34.431 T:4507    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.hbogoeu/?mode=2&name=4%20BLOCKS%20(2017)&url=https%3a%2f%2fplapi.hbogo.eu%2fv8%2fContent%2fjson%2fPOL%2fAPTV%2fa58814c5-b712-6c6a-6994-f1b57497b26d%2f
2021-08-03 20:10:34.434 T:3409    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hbogoeu/?mode=2&name=4%20BLOCKS%20(2017)&url=https%3a%2f%2fplapi.hbogo.eu%2fv8%2fContent%2fjson%2fPOL%2fAPTV%2fa58814c5-b712-6c6a-6994-f1b57497b26d%2f) failed

**Screenshots**
http://i.imgur.com/XdiB3z0.png

**Operating System**
Linux (x86/x64)
Linux (ARM)

**Comment by gwozniak** [comment]
Confirming it seems that only series part is affected.

**Comment by gwozniak** [comment]
And this is the example of failing request:
grzebek@mir3 ~ $ curl http://plapi.hbogo.eu/v7/Content/json/ENG/ANMO/679d34f1-0a4e-1276-264b-3c094cd6a3a5/ | jq . 
                                                                                                                                                               
{
  "Error": {
    "Code": "1.8",
    "Details": "Parameters - ErrorCode: ERROR_GROUP_CALL_BLOCKED, Language: ENG",
    "DisplayMessage": "A new version of the application is available. Please update to continue watching the best original series and hit movies",
    "Message": "A new version of the application is available. Please update to continue watching the best original series and hit movies"
  },
  "ErrorMessage": "A new version of the application is available. Please update to continue watching the best original series and hit movies",
  "ObjectType": 5,
.......
}

**Comment by arvvoid** [comment]
Hello, i'm limited with time at the moment. But will look into it. Most likely the changes causing this catch on on all platforms, this might take longer to fix then previous times.
For the moment the only valid workaround is use the search function for series. Movies are not affected.

This problem is not affecting the spain/nordic region.

**Comment by BlackGlassSkin** [comment]
> For the moment the only valid workaround is use the search function for series. Movies are not affected.

for series also "add to my list" works for whole seasons

**Comment by arvvoid** [comment]
@kkraszy @gwozniak @BlackGlassSkin Hello, there is a fix in #201 

Please test and let me know. I made a couple of quick tests and is ok, just need couple of more tests and will release.

**Comment by arvvoid** [comment]
Fixed in release 2.7.8

**Comment by krokodylowy** [comment]
Hi
This version seems to be not available in Matrix repo so message now appears.

**Comment by arvvoid** [comment]
@krokodylowy Hello, 2.7.8 is available in both Leia and Matrix repository and should fix the issue. If you running 2.7.8 and still experience the problem please open a bug report and post  a full debug log (that might mean something changed again on hbo end)
