### ISSUE TITLE
[SUPPORT] Automatic choice of subtitle language 

### ISSUE THREAD

**Issue by VadVoci** [arvvoid/plugin.video.hbogoeu#211]
* [x] Are you running the latest version?

**Befor sending the support request this resources can be checked:**

[Kodi Forum thread](https://forum.kodi.tv/showthread.php?tid=339798) |
[Project wiki](https://github.com/arvvoid/plugin.video.hbogoeu/wiki) | 
[FAQ](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/FAQ) | 
[Troubleshoot](https://github.com/arvvoid/plugin.video.hbogoeu/wiki/Troubleshoot)

* [x] I have already checked all resources above

* [ ] I just want to provide feedback or get in touch

**Please enter your question or feedback**

If you use subtitles often, you may find that clicking on Subtitles > Subtitles Settings every time you start a video, can be a bit annoying.
I mean the plugin.video.hbogoeu application in this case.
Every time I start playing a movie in HgoGo, it automatically loads my subtitles, but in English, because it's the first in a list of four subtitles:
English- (external) (1/4)
Unknown-RON (external) (2/4)
English (3/4)
Romanian (4/4)

I am interested in the option (4/4), respectively the Romanian subtitles, the last one in the list of choices.
Could I configure, or could it be implemented in the future to be able to choose which option to have automatically?

I uploaded some sample photos :

    https://i.imgur.com/MWNAwkx.jpg
    https://i.imgur.com/gWvzwYa.jpg
    https://i.imgur.com/VdJstGl.jpg
    https://i.imgur.com/GzM90xC.jpg
    https://i.imgur.com/zjNJcR7.jpg

Trying to set up a permanent choice of preferences does not seem to work .

Later Edit: 
It's done. In the plugin settings, "Always use the default operator language" it was ticked. I took out that check mark, and now it works fine.

**Comment by arvvoid** [comment]
Glad it's solved, for future reference I'm linking the forum posts: https://forum.kodi.tv/showthread.php?tid=339798&pid=3061098#pid3061098, https://forum.kodi.tv/showthread.php?tid=339798&pid=3061108#pid3061108, https://forum.kodi.tv/showthread.php?tid=339798&pid=3061144#pid3061144
