### ISSUE TITLE
[QUESTION] What about HBO Max?  

### ISSUE THREAD

**Issue by sorin-pop** [arvvoid/plugin.video.hbogoeu#213]
This is just a simple question.

I understand that soon HBO Go is going to become HBO Max soon (with some changes I think).

I was wondering if the owners of this project know about this and are prepared for this new stuff?

**Comment by arvvoid** [comment]
Hello,

HBO Max is a completely different platform and this add-on will become obsolete when all regions switch to HBO Max. There is a different add-on already available (not in the Kodi add-on repository at the moment), check : https://forum.kodi.tv/showthread.php?tid=358484.

I will maintain this add-on until is useful and there are regions still using HBO Go.
My region is switching to HBO Max 8.3.2022.

**Comment by arvvoid** [comment]
The add-on reached End of Life. The Hbo Go service has been replaced in all regions by Hbo Max. A Hbo Max add-on can be found here https://forum.kodi.tv/showthread.php?tid=358484
