### ISSUE TITLE
[BUG] Subtitles are not working on some titles

### ISSUE THREAD

**Issue by awdAvenger** [arvvoid/plugin.video.hbogoeu#22]
* Using version. 2.0.10-beta26.

**Describe the bug**
Subtitles for not always work on some shows. It seems to be consistent for any given show if the subtitles works or not.

I'm connecting to HBO Nordic in Norway and one show that does not have working subs is The Office (US).

Subtitles for this show works fine in the browser, but they do not seem to be detected in this add-on. No subtitles are available from the subtitles menu.

Subtitles seem to work for most other shows.

Here is what happens in the log when starting a new episode:
https://pastebin.com/nEab3WvL

Please tell me if there is any other information I can supply.

**Operating System**

* [X ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Additional informatin on the environment**
Using Arch Linux and Kodi 18.3.

**Comment by arvvoid** [comment]
Hello tnx for reporting. You posted only a partial log, missing any useful information. Please recreate the problem, start a show with working subtitles and then one where the subtitles don't work with debug loggin enabled, and post a **full** debug log.

Like stated in the README:
> PLEASE IF YOU ARE REPORTING AN ISSUE PROVIDE Kodi Debug Logs: https://kodi.wiki/view/Log_file/Easy . Without a full log is difficult or impossible to guess what's going on.

**Comment by awdAvenger** [comment]
Sorry for that, heres a full log:

https://paste.ubuntu.com/p/vxzrNJp2Jv/

The first show I started was The Handmaid's Tale, S03E01 (at around 07:14:27.946 in the log), where the subtitles work fine.

Then I started The Office S04E02 (~07:14:52.730) where the subtitles does not work.

I just ran the shows for 20-30 seconds to see if the subtitles worked or not.

Thank you for you assistance.

**Comment by arvvoid** [comment]
Found the problem

`2019-07-22 07:14:52.622 T:140498547226368   DEBUG: [plugin.video.hbogoeu] Force subtitles enabled, downloading and converting subtitles in: /home/avenger/.kodi/userdata/addon_data/plugin.video.hbogoeu/subs/1f10ced-0049ef2147c/
2019-07-22 07:14:52.623 T:140498547226368   DEBUG: [plugin.video.hbogoeu] Processing subtitle language code: en_hbon URL: https://static.hbonordic.com/1f10ced-0049ef2147c/fbbcdf16b5154f2e9f6ee0bcb5471912.xml
2019-07-22 07:14:52.725 T:140498547226368   DEBUG: [plugin.video.hbogoeu] Unexpected error in subtitles processing
2019-07-22 07:14:52.725 T:140498547226368   DEBUG: [plugin.video.hbogoeu] Play url: <xbmcgui.ListItem object at 0x7fc8a83924e0>`

The ttml to srt converter fail for The Office. It looks like the subtitles for the Office are provided in a slightly different format...
Will investigate deeper when I catch some extra time.

THE OFFICE SUBTITLES: https://static.hbonordic.com/1f10ced-0049ef2147c/fbbcdf16b5154f2e9f6ee0bcb5471912.xml

HANDMAIDENS TAIL SUBTITLES (STANDARD TTML like other shows): https://static.hbonordic.com/1f10ced-010ff6e04f2/86b1578be5644cf2ae1c4f4bd97ce9a9.xml
