### ISSUE TITLE
[BUG] HBO Nordic does not list every movie or TV series available 

### ISSUE THREAD

**Issue by haakobja** [arvvoid/plugin.video.hbogoeu#24]
* [x] Are you running the latest version?

**Describe the bug**
The addon does not list the full selection of available movies or TV series when selecting the "All Series" or "All movies". The TV series ends at S, even though I know shows that start with W are available. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open HBO Go EU addon
2. Go to Series
3. Go to "All series" 
4. Scroll down to last element in the list. 

**Expected behaviour**
The list should include every TV series available on HBO nordic.

**Comment by arvvoid** [comment]
Please enable debug logging in Kodi recreate the problem and then post a full debug log. In the redme there is a link to instructions how to do that.
I will be away for 10 days or more, will look into it when i'm back :)

**Comment by pedriterman** [comment]
I have the exact same problem

**Comment by arvvoid** [comment]
I will need a full debug log recreating the problem to fix this since I don't have access to the "region".

**Comment by haakobja** [comment]
Does the following debug-log help?
https://paste.ubuntu.com/p/4Pp7b4GC9m/

**Comment by arvvoid** [comment]
From the log looks like all the items returned in the category all series by hbo go get properly added.

https://api-hbon.hbo.clearleap.com/cloffice/client/web/browse/f5dde064-495d-41dc-8cd7-cbb76baaf8d0?language=en_hbon

The last item added in the log is SMILF and the last item in the returned xml is SMILF. Can you post a screenshot showing the first and last item in the list?
Please note that the addon simply retrieves the xml from hbo go and list everything in it in the same order provided from hbo go. 
(I think the top priority is to add search and my list function to the nordic/spain region in the add-on)

Can you check the same category using the browser/official client and see if the list is the same.

**Comment by haakobja** [comment]
The link you posted seems to return the same items that I see in the plugin. It is a total of 200 items in the file, but the `clearleap:totalResults`-tag says it should be 281. So there are 81 items missing from the list. 

I also logged in on `hbonordic` and checked the *All series* list, which has the same GUID as you posted. When looking at the calls that the web client did, it seems like API is paginated. Every time I came to the bottom of the page, it loaded the next 20 results.

The API have the following query params:

| Param | Description |
|--------|------------- |
| `max`    | The maximum number of items to retrieve, seems to be capped at 200 |
| `offset` | 0 based, marks the first result to be fetched. Offset is inclusive |

A link with both `offset=n` and `max=m` is fetching results from ` n to n+m`

This link fetches the rest of the results
https://api-hbon.hbo.clearleap.com/cloffice/client/web/browse/f5dde064-495d-41dc-8cd7-cbb76baaf8d0?offset=200

**Comment by arvvoid** [comment]
@haakobja Ok with the info you provided this is an easy fix. I will post a test version when it is ready and if all is ok will make a release.

**Comment by arvvoid** [comment]
@haakobja Hello, please download the current master https://github.com/arvvoid/plugin.video.hbogoeu/archive/master.zip use the install from zip function in Kodi and test. If all is ok will make a release.

**Comment by haakobja** [comment]
I did a quick test, and `All series` and `All Movies` seems to list everything. Howerver, the listing seems to take a while for the movies. So maybe it is possible to optimise the retrieval a bit? But that's just nitpicking as it currently lists all movies and all series.

**Comment by pedriterman** [comment]
I can't install it in my fire tv stick. It says that can't satisfy inpustream dependencies.

**Comment by arvvoid** [comment]
@pedriterman I bumped the requirment for inputstream.adaptive to the latest version witch is out for some time now so thought all platforms cached up by now. I will drop the requirment for the release but is recomended to use the latest version of inputstream.adaptive if possible.

**Comment by pedriterman** [comment]
I updated Kodi to 18.3 and everything is working great. Can't tell if now is slower because fire TV is slow as it is

**Comment by arvvoid** [comment]
@pedriterman ok perfect

@haakobja @pedriterman All Series and All Movies lists are fairly long and have to retrieve images for each item as well so it can get slow on slower devices. There is no caching mechanism implemented yet.
It could be made faster by mainteing the pagination and having to click next page at the bottom of the list but personally, find that annoying especially if you trying to find something at the bottom of the list. So much better imo a little longer load time on long lists but having all in one list that can be scrolled fast and filtered (there is no way in Kodi to dynamically add to the list and dynamically loading while scrolling).

To solve the slowness on longer lists on slower devices I plan to implement a caching system and create a service for the add-on. The service will handle the library integration and keep the library in sync with the exported items, and will also pre-cache frequently used list by the user when the device is idle. As part of this, i plan to implement TMDB integration to get better images for the items, not just the ones provided by hbo. But this is along-term plan that will wait until i have more free time.

**Comment by haakobja** [comment]
My immediate thought when I looked at the code, was to create batches and retrieve them in parallel. But it might not speed up the process significantly.  The main functionality of retrieving every item is there, so for me that's good enough

**Comment by arvvoid** [comment]
I went for the quick and simple solution for now to fix the functionality, will make a release today. 
When i find some time i will do some optimization-restructure on global add-on level.

**Comment by arvvoid** [comment]
Fixed

**Comment by arvvoid** [comment]
@all-contributors please add @haakobja  for bug
