### ISSUE TITLE
[SUPPORT] Left in unstable state, plugin does not play

### ISSUE THREAD

**Issue by jbrepogmailcom** [arvvoid/plugin.video.hbogoeu#26]
* [ ] Are you running the latest version?
Yes

**Describe the bug**
I got info from plugin that some software from Chrome needs to be installed. I chose YES but then when it tried to start 2GB download I cancelled it. Now it seems that plugin "thinks" that newer version of Chrome has been installed, but it was not. Movies do not play.

I tried to completely uninstall plugin and wipe settings, but after new installation it still does not play. I think I need to reset the plugin so it downloads Chrome again. But it is not reset by clearing settings. How do I reset it manually?

**To Reproduce**
When asked to update chose YES. When asked to download 2GB answer NO. Then no movies play.

**Expected behaviour**
Movies play

## Debug log
No log file is shown

[Please include a link to your debug log. Follow these instructions https://kodi.wiki/view/Log_file/Easy]

**Screenshots**

**Operating System**

* [ ] Linux (ARM)

**Additional informatin on the environment**

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Additional context**

**Comment by arvvoid** [comment]
This is not an add-on bug. Old versions of widevine are not usable anymore becouse of content providers changes. Recently inputstream adaptive helper got updated to be able to install the latest version of widevine. For arm devices the only legal source of the widevine library is the chromeos img from witch is then extracted, canceling the download and instalation leaves you with the old widevine version witch doesn t work anymore. You can delete the content of the cdm forler in kodi profile to triger new widevine instalation. The developers of inputstream helper plan to add a force reinstall option in the future as well.

**Comment by jbrepogmailcom** [comment]
Thank you. I confirm that deleting content of .kodi/cdm folder worked.
