### ISSUE TITLE
Make language files for all supported countries

### ISSUE THREAD

**Issue by arvvoid** [arvvoid/plugin.video.hbogoeu#3]
Current status of translations (_STATUS LAST UPDATED 08/1/2021 12:07_):

**[English](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.en_gb/strings.po)** 102 strings in total / POT file

**OK** - ✔, **NEED UPDATE** - ✍, **BAD NEED WORK** - ✖ **MACHINE TRANSLATED** - 🖥️‼️

| Language | Status | ISO code | Untranslated | Last translator | Previous translators |
|-----------|--------|-------------|--------------|----------------|---------------------|
|[Bosnia and Herzegovina](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.bs_ba/strings.po)|✖|bs_ba|all|🖥️‼️||
|[Bulgaria](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.bg_bg/strings.po)|✖|bg_bg|all|🖥️‼️||
|[Croatia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.hr_hr/strings.po) |✔|hr_hr|0| @arvvoid||
|[Czech Republic](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.cs_cz/strings.po) |✔ |cs_cz|0|@CZJohny|@Ike201|
|[Hungary](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.hu_hu/strings.po) |✔|hu_hu|0|@Ajnasz||
|[Macedonia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.mk_mk/strings.po)|✖|mk_mk|all|🖥️‼️||
|Montenegro|✖|cnr_me|all|||
|[Polonia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.pl_pl/strings.po)| ✔|pl_pl|0|@barqqlsky|@kowalmisiek|
[Portugal](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.pt_pt/strings.po)|✖|pt_pt|all|🖥️‼️||
|[Romania](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.ro_ro/strings.po)| ✔|ro_ro|0|@tmihai20||
|[Serbia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.sr_rs@latin/strings.po)|✖|sr_rs@latin|all|🖥️‼️||
|[Slovakia](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.sk_sk/strings.po)|✔|sk_sk|0|@durip||
|[Slovenija](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.sl_si/strings.po)|✖|sl_si|all|🖥️‼️||
|[Spain](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.es_es/strings.po) |✍|es_es|2|@boblo1|@jhdgghost|
[Norway](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.nb_no/strings.po)|✖|nb_no|all|🖥️‼️||
[Denmark](https://github.com/arvvoid/plugin.video.hbogoeu/raw/51fc68c41ec2c65e9bf9e413cdd89156dad926ce/resources/language/resource.language.da_dk/strings.po)|✖|da_dk|all|🖥️‼️||
|[Sweden](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.sv_se/strings.po)| ✔|sv_se|0|@Sopor|@macardi|
|[Finland](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.fi_fi/strings.po)|✔|fi_fi|0|@jumakki||

_When possible if no translation is available an initial machine translation has been provided to make it easier for new translators._

**How to translate?**

Download the existing language file for the language you want to translate and make corrections

OR

[Download the English POT file](https://github.com/arvvoid/plugin.video.hbogoeu/raw/master/resources/language/resource.language.en_gb/strings.po) and translate the strings, post here the translated PO file I will do the rest and your translation will be included in the next release. 

**It's easier if you use a specialized tool for PO files editing.** https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

How a translated PO file should look like?

[See the Croatian translation as an Example](https://github.com/arvvoid/plugin.video.hbogoeu/blob/master/resources/language/resource.language.hr_hr/strings.po):

```
msgctxt "#30000"
msgid "ENG"
msgstr "HRV"

msgctxt "#30001"
msgid "ERROR"
msgstr "GREŠKA"

msgctxt "#30002"
msgid "Setup failed"
msgstr "Postavljanje nije uspjelo, pokušajte ponovno"

...

msgctxt "#30006"
msgid "Error sending data to Hbo Go"
msgstr "Pogreška slanja podataka na HBO Go"

msgctxt "#30008"
msgid "Communication error, returned STATUS: "
msgstr "Pogreška u komunikaciji, vraćeni STATUS: "

msgctxt "#30009"
msgid "The content is available from:"
msgstr "Sadržaj je dostupan od:"

...

#: 
msgctxt "#30101"
msgid "PLEASE DON'T CONTACT YOUR OPERATOR SUPPORT ABOUT THIS ADD-ON, THIS IS AN UNOFFICIAL ADD-ON AND HAVE NO OFFICIAL SUPPORT! COMMUNITY HELP CAN BE FOUND ON THE ADD-ON GITHUB PAGE OR KODI FORUM"
msgstr "MOLIMO VAS DA NE KONTAKTIRATE PODRŠKU SVOG OPERATERA O OVOM ADD-ON, TO JE NESLUŽBENI ADD-ON I NEMA SLUŽBENU PODRŠKU! POMOĆ ZAJEDNICE MOŽETE PRONAĆ NA ADD-ON GITHUB STRANICI ILI NA KODI FORUMU"

#: 
msgctxt "#30102"
msgid "Operators"
msgstr "Operatori"

...

```

**Comment by jhdgghost** [comment]
[strings.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3100342/strings.txt)
Hello i submit the Spanish Translation of the file. If someone want to review it go ahead.

**Comment by arvvoid** [comment]
> [strings.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3100342/strings.txt)
> Hello i submit the Spanish Translation of the file. If someone want to review it go ahead.

Added in #13

**Comment by macardi** [comment]
[strings_swe.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3111229/strings_swe.txt)

Swedish translation.

**Comment by jumakki** [comment]
Finnish translations:
[strings_fin.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3113989/strings_fin.txt)

**Comment by tmihai20** [comment]
Romanian translation from me. If there are any issues, please mention me or reply and I will take care of them. I chose RO and ro as the denomination for Romania, I hope that is correct.

[strings-ro.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3165312/strings-ro.txt)

**Comment by Ike201** [comment]
Czech translation:
[strings_cze.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3220101/strings_cze.txt)

**Comment by arvvoid** [comment]
@all-contributors please add @tmihai20  for translation

**Comment by arvvoid** [comment]
@all-contributors please add @Ike201  for translation

**Comment by Bossillio** [comment]
Russian translation
[REMOVED]

**Comment by arvvoid** [comment]
@Bossillio hello, no binary files please only translations in txt format with utf-8 encoding are allowed

**Comment by arvvoid** [comment]
To all translators: all language files need updating

**Comment by tmihai20** [comment]
What is a Home Category or a Home List? I do not understand it so I can translate it in Romanian (cc @arvvoid ). Is it like a personalized category or list?

**Comment by arvvoid** [comment]
Hello @tmihai20 Home Category is the root category the first thing displayed when opening hbo go where all links to other subcategories are. Home lists are the lists displayed on the home screen like Fetured, Weekly Top, ecc.., ecc..

Basically now there is an option (not enabled by default) to make the add-on not display links to all these lists directly on the first screen but instead display Home lists menu item on the initial screen then display all these lists only if that menu item is entered.

**Comment by tmihai20** [comment]
So it would be a base like category, right? I still cannot think of a translation for Home List or Category. I have translate Home as Base in Romanian. I have also made minor changes to some of the existing strings. I hope they are ok. If there is any Romanian person with an alternative for Home Category/List, please reply and cc me. Updated English strings can be found below.

**Comment by boblo1** [comment]
@arvvoid, I have reviewed the spanish translation and the updated PO file is attached to this message. Before submitting it to the repository, please check the first lines (then you can safely remove them).
Regards.
[strings.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3964338/strings.zip)

**Comment by Ajnasz** [comment]
Here is the Hungarian translation.

[strings_hu.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3970383/strings_hu.po.txt)

**Comment by arvvoid** [comment]
@tmihai20 @boblo1 @Ajnasz Tnx for the updated translation I will check and include in the next release.

**Comment by jumakki** [comment]
Finnish translations.
[strings_fi.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3972503/strings_fi.po.txt)

**Comment by boblo1** [comment]
> @tmihai20 @boblo1 @Ajnasz Tnx for the updated translation I will check and include in the next release.

First of all, check the first lines of my translation. They contain corrections to original english messages. When those corrections are checked and applied, you can remove those lines.
Hope this helps

**Comment by tmihai20** [comment]
@boblo1 is correct. We need to correct the English strings a little bit. Here is my updated strings in Romanian with the corrected strings in English included.
[strings.ro.v2.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3972661/strings.ro.v2.txt)

I made this pull request, try to review it https://github.com/arvvoid/plugin.video.hbogoeu/pull/89.

**Comment by arvvoid** [comment]
@boblo1 @tmihai20 Merged https://github.com/arvvoid/plugin.video.hbogoeu/pull/89

**Comment by boblo1** [comment]
> @boblo1 @tmihai20 Merged #89

@arvvoid : You forgot to commit my translation. Thanks.

**Comment by arvvoid** [comment]
@boblo1  like I said the updated translations will be included in the next release, I didn't forget anything.  I simply merged PR #89  now

**Comment by arvvoid** [comment]
@all-contributors please add @boblo1 for translation

**Comment by arvvoid** [comment]
Language files have been updated and sync-ed in bf716f45c96d20e4d73e296dc33eb534afe68f27 some new strings have been added for the send elapsed time to Hbo go update (EU only for now) so new updates to the language files are necessary

**Comment by arvvoid** [comment]
Language files got updated in the last commit

**Comment by jumakki** [comment]
Finnish texts updated
[strings_fi.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3977927/strings_fi.po.txt)

**Comment by boblo1** [comment]
Here is the updated Spanish translation. I have also checked the original messages in English again and there were still some errors, I have corrected them. Since I still cannot make pull requests, I have attached both files to this post.

@arvvoid : my suggestion is that you use a file editor with autocompletion, e.g. Notepad++. It's free, so you'll always type words without errors. In addition, you could use an online translator to check if your messages are well written in english. Hope this helps.

[strings-en_GB.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3979041/strings-en_GB.zip)
[strings-es_ES.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3979053/strings-es_ES.zip)

**Comment by arvvoid** [comment]
@boblo1 Tnx for your contribution. I will check and resync the language files if needed with Poedit so nobody have to do it manually after the corrections to English.
 I already use Poedit, just wasn't in my focus to do this now, so tnx for saving a lot of time.

**Comment by arvvoid** [comment]
@boblo1 and all translators all language files are now resynced after corrections to English so all language files include the corrections to the msgids

**Comment by Ajnasz** [comment]
Updated the Hungarian translations

[strings_hu.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3982889/strings_hu.po.txt)

**Comment by tmihai20** [comment]
I have made changes directly by creating a pull request https://github.com/arvvoid/plugin.video.hbogoeu/pull/96. I hope this is ok.

**Comment by arvvoid** [comment]
@tmihai20 Merged :)

**Comment by boblo1** [comment]
@arvvoid : is there a way to download only one file instead of downloading the whole project? And how could I do a PR? I don't think I have the necessary permissions in your repository. Thank you.

**Comment by arvvoid** [comment]
@boblo1 yes, when you viewing a file on GitHub there is an option to show the **RAW** version, you can view the RAW version and simply save it or use the save link option of your browser depending on the browser you using. (for language files i made links for direct download on the initial post of this issue as well). Anyone can open a pull request, there is plenty of information on GitHub help pages and tutorials online.  

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Ike201** [comment]
latest version of PO for Czech lang:
[strings.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3988012/strings.po.txt)

**Comment by boblo1** [comment]
>Anyone can open a pull request, there is plenty of information on GitHub help pages and tutorials online.
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

I tried to make a pull request and GitHub claim that a clone of this project should be created first because I don't have direct write permission to this repository. Is this normal?

**Comment by boblo1** [comment]
>Anyone can open a pull request, there is plenty of information on GitHub help pages and tutorials online.
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

I tried to make a pull request and GitHub claim that a clone of this project should be created first in my repository with new changes, because I don't have direct write permission to this repository. Is this normal?

**Comment by arvvoid** [comment]
@boblo1 yes that's normal, please read the links above and read this https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-collaborative-development-models. This now is going offtopic on this issue. 
You have to do your own fork, preferably create a themed branch push your changes to your branch in your fork (clone) and then open a pull request from your branch to this repository (the upstream repository).
It's your responsability to keep your fork up to date with upstream, and always a good idea to pull changes from upstream before starting to work on your new changes/features.

**Comment by boblo1** [comment]
> @boblo1 yes that's normal, please read the links above and read this https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-collaborative-development-models. This now is going offtopic on this issue.
> You have to do your own fork, preferably create a themed branch push your changes to your branch in your fork (clone) and then open a pull request from your branch to this repository (the upstream repository).
> It's your responsability to keep your fork up to date with upstream, and always a good idea to pull changes from upstream before starting to work on your new changes/features.

Got it. Thanks and sorry for going off-topic.

**Comment by arvvoid** [comment]
When possible if no translation is available an initial machine translation has been provided to make it easier for new translators

**Comment by arvvoid** [comment]
@Ike201 @Ajnasz @kowalmisiek @tmihai20 @boblo1 @macardi @jumakki @jhdgghost

Hello, all language files need an update before the next release in Kodi repo.

**Comment by Ike201** [comment]
latest version of PO for Czech lang:
[strings.po.2020-02-08.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4174074/strings.po.2020-02-08.txt)

**Comment by boblo1** [comment]
Spanish translation updated.

@arvvoid: Please revise some occurrences of the text 'Hbo go' in original english messages and change them with text 'HBO Go'. The spanish translation already has this fix.

[strings_ES.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4175094/strings_ES.po.txt)

**Comment by jumakki** [comment]
Finnish: 
[strings.fi.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4177074/strings.fi.po.txt)

**Comment by tmihai20** [comment]
Romanian updated with PR #115 .

**Comment by Ajnasz** [comment]
Hey!

I have two questions:
What is `generic "video" media type`?
Is there any other type of caching or can i say "Clear cache"?

Thanks!

**Comment by Ajnasz** [comment]
I checked the code what is generic video media type.
What do you think to not add the setting, instead return it if the content is mixed?
Something like this: https://github.com/Ajnasz/plugin.video.hbogoeu/commit/92651ff77d23296d8d2bb4007c8c5a04848ddc8e

**Comment by arvvoid** [comment]
@Ajnasz Hello, set "generic Video media" type is how the add-on behaved before. Set always Video (as folder type). What view types are available for various folder types depends on the skin used. So with the default Kodi skin using the video type is ok but on many skins, that behave poorly and miss a lot of information.  So now the add-on by default keep track of the number of movies/tv-shows/episodes in a folder and set the content-type based on the majority of the content in the folder. Found that behavior works best on many different skins, avoided setting generic video on mixed on purpose.

Thanks all for the translations will include them soon. Also, the current master needs testing across few days of usage, especially for the Nordic/Spain region I can't test myself.

**Comment by arvvoid** [comment]
@Ajnasz yes you can say just use Clear cache, currently, there is only one type. My first implementation of the caching system had the request cache and had the image cache as well but gave up on that since I found out Kodi does image caching already and it does it async, that behave better, and folders are visualized faster, so I eliminated the image cache from the add-on and left only the requests cache which drastically reduces the need for repetitive API calls from HBO go within the same day (ofc dynamic lists that change dynamically in real-time are automatically put on cache exclude list).

**Comment by arvvoid** [comment]
Submitted languages updated

**Comment by boblo1** [comment]
Pending message string translated.
[strings_ES.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4220675/strings_ES.po.txt)

**Comment by arvvoid** [comment]
Ping to translator @Ike201 @Ajnasz @kowalmisiek @tmihai20 @macardi @jumakki @jhdgghost

Most language files need just a minor update, some need a major update.

**Comment by jumakki** [comment]
Finnish updated: 
[strings.fi.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4231923/strings.fi.po.txt)

**Comment by tmihai20** [comment]
Made PR #123. I also correct a small typo in the newly added English string. It should be corrected in all strings if possible.

**Comment by arvvoid** [comment]
I will wait till the beginning of the next week for other translators to have time to submit the translations and then gonna send what's done so far to the Kodi repo. If you don't make it for this submission no worries will be for the next.

A pre-release with updated translations is already available under releases.

**Comment by arvvoid** [comment]
@Ajnasz @Ike201 @tmihai20 @boblo1 @jumakki Language files need minor updates.

@kowalmisiek Polonia translation needs a major update 12 untranslated 15 to check marked as fuzzy

@macardi Swedish translation needs a major update 23 untranslated 3 to check marked as fuzzy

Please if there are any strings marked as fuzzy in your files check the translation, correct if needed and unmark fuzzy.

**Comment by jumakki** [comment]
Finnish translations: 
[strings.fi.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4345527/strings.fi.txt)

**Comment by arvvoid** [comment]
Removing languages because unmaintained: 

- Bosnia and Herzegovina
- Bulgaria, Macedonia
- Portugal
- Serbia
- Slovakia
- Slovenija
- Norway
- Denmark 

Candies for future removal: 

- Polonia
- Sweden

If an updated and corrected translation gets submitted those languages will be reincluded in master and future releases.
The removed files can be retrieved from old commits simply by clicking the link in the first post.

**Comment by tmihai20** [comment]
Made PR #133 for Romanian translation.

**Comment by durip** [comment]
Hi @arvvoid , 
I did a Slovak translation.
[strings_SK.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4365169/strings_SK.po.txt)

**Comment by boblo1** [comment]
@arvvoid : I cannot find the untranslated message string in the PO file included in the chart (spanish language). Could you help me?

**Comment by arvvoid** [comment]
@durip tnx will check and include soon

hello, @boblo1 its this string, it's already machine-translated but marked at fuzzy so you have just to check and if it's on just remove the #fuzzy (if you use something like PO edit or other PO editor there will be a checkbox if you edit manually you can just remove the #fuzzy preceding the translation)
```
#, fuzzy
msgctxt "#30737"
msgid "Kids only mode"
msgstr "Modo solo para niños"
```

**Comment by boblo1** [comment]
> @durip tnx will check and include soon
> 
> hello, @boblo1 its this string, it's already machine-translated but marked at fuzzy so you have just to check and if it's on just remove the #fuzzy (if you use something like PO edit or other PO editor there will be a checkbox if you edit manually you can just remove the #fuzzy preceding the translation)
> 
> ```
> #, fuzzy
> msgctxt "#30737"
> msgid "Kids only mode"
> msgstr "Modo solo para niños"
> ```

I understand. Here you go:
[strings_ES.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4366232/strings_ES.po.txt)

**Comment by arvvoid** [comment]
Tnx @boblo1

**Comment by arvvoid** [comment]
@all-contributors please add @durip for translation

**Comment by arvvoid** [comment]
@Ajnasz @Ike201 @tmihai20 @boblo1 @jumakki Language files need minor updates.

@kowalmisiek Polonia translation needs a major update 17 untranslated 15 to check marked as fuzzy

@macardi Swedish translation needs a major update 31 untranslated 3 to check marked as fuzzy

All files are already synced with new POT

**Comment by Ike201** [comment]
czech language: 

[strings.po.2020-04-15.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4487427/strings.po.2020-04-15.txt)

**Comment by boblo1** [comment]
Spanish translation updated:
[strings_ES.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4487706/strings_ES.po.txt)

**Comment by jumakki** [comment]
Finnish: [strings.fi.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4487802/strings.fi.po.txt)

**Comment by Ike201** [comment]
sorry... better version:

[strings.po.2020-04-15.v2.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4488665/strings.po.2020-04-15.v2.txt)

**Comment by tmihai20** [comment]
As always, added a PR (#152) for Romanian strings.

**Comment by arvvoid** [comment]
Thanks for the submissions, all sent so far merged :)

**Comment by durip** [comment]
Slovak translation updated:
[strings.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/4505236/strings.po.txt)

**Comment by arvvoid** [comment]
@durip tnx, merged

**Comment by Txato** [comment]
Hello, I know it is not the way to ask these questions, but could you tell me how to listen to the content of the addon in Spanish? Because when I install the addon I select Spain and the sound comes out in English. Just let me put subtitles in Spanish.
Thanks and best regards.

**Comment by arvvoid** [comment]
@Txato Hello, please use the forum for general questions or open a new support issue with your question. These will be deleted from here in 24h. 
Not all content will have audio tracks in Spanish that entirely depend on Hbo and the content creator, those that do, you can select the audio track from the audio settings during playback. Similar to subtitles you can set in Kodi preferred audio track language (it will fall back to default English usually if the selected language is not available). For more detailed answers ask through proper channel.

**Comment by arvvoid** [comment]
Hello, a new release will be made soon. I will wait for translation submissions until Friday 18/12/2020, publishing a new release on Saturday 19/12/2020.
Most maintained translations need only minimal effort 2 strings (non-critical, very rarely seen).

@Ike201 @Ajnasz @kowalmisiek @tmihai20 @durip @boblo1 @Sopor @jumakki

**Comment by durip** [comment]
Slovak translation updated:
[strings.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/5691501/strings.po.txt)

**Comment by CZJohny** [comment]
Added missing 2 translations - Czech. 

[strings.po.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/6576127/strings.po.txt)

**Comment by Ike201** [comment]
S pozdravem / Best regards
Michal Valdman


út 1. 6. 2021 v 14:17 odesílatel CZJohny ***@***.***> napsal:

**Comment by arvvoid** [comment]
Add-on  End Of Life
