### ISSUE TITLE
Using VLC as an external player

### ISSUE THREAD

**Issue by bugproof** [arvvoid/plugin.video.hbogoeu#31]
Trying to play using VLC:

![image](https://user-images.githubusercontent.com/3116731/65987730-b41c1280-e486-11e9-8e61-162894d4c823.png)

![image](https://user-images.githubusercontent.com/3116731/65987641-8931be80-e486-11e9-946d-27283bcf7de2.png)

any idea why this happens?

playercorefactory.xml

```

<?xml version="1.0" encoding="UTF-8"?>
<playercorefactory>
    <players>
        <player name="VLC" type="ExternalPlayer" audio="false" video="true">
            <filename>C:\Program Files\VideoLAN\VLC\vlc.exe</filename>
            <args>"{1}" -f --video-on-top /close</args>
            <hidexbmc>false</hidexbmc>
            <hideconsole>false</hideconsole>
            <warpcursor>none</warpcursor>
        </player>
    </players>

    <rules action="prepend">
        <rule internetstream="True" player="VLC"/>
    </rules>
</playercorefactory>


```

it's interesting because I can see HBO logo just for 1 moment despite all this

It would be really great to be able to use VLC. I prefer it much more on desktop

**Comment by arvvoid** [comment]
Hello, this is not a supported use case, and probably will never be, VLC, as far as I know, don't have the necessary DRM support to play DRM protected streams. https://wiki.videolan.org/Digital_Restrictions_Management/
This would need changes in VLC and VLC to add DRM support. What that context menu does, it simply passes the "file" to VLC, and VLC would need to handle all the rest, including the Hbo go login and DRM.

Also, this is the wrong address for VLC support.

**Comment by bugproof** [comment]
Thanks for your answer. So what I would need is some kind of plugin that is able to decrypt Widevine protected stream. That's an interesting idea for the project. I wonder if it's doable.

**Comment by arvvoid** [comment]
No problem. No you haven't understood correctly, you would need to add to VLC the ability to use the widevine library (proprietary closed source, https://en.wikipedia.org/wiki/Widevine) to decrypt/decode the content like web browsers do.
In Kodi that is handled with a binary add on inputstream.adaptive source here: https://github.com/peak3d/inputstream.adaptive witch add DRM support and adaptive stream support to Kodi.

Keep in mind that for licensing reasons you can't distribute/redristribute the widevine library without an explicit license from Google. That's handled with inputstream.helper add-on in Kodi which guides the user with the process of retrieving from a legal source and putting the library in the right place.

Everything is doable but would require most likley considerable effort/hours.
