### ISSUE TITLE
[BUG] Script error after entering credentials

### ISSUE THREAD

**Issue by mata007** [arvvoid/plugin.video.hbogoeu#37]
* [x] Are you running the latest version?

**Describe the bug**
After selecting the region and entering the login name and password, only a popup with the HBO GO EU plugin error will be displayed.
[LOG PASTE IN MSG REMOVED]

## Debug log
[Link to full log is here.](https://raw.githubusercontent.com/mata007/error-logs/master/kodi-hbo-go-eu-credentials-error.log)

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

**Additional informatin on the environment**

Kodi (18.4 Git:20190831-3ade758ceb). Platform: Android ARM 32-bit
Running on Amlogic Lepší.TV Box with Android 6.0.1 API level 23, kernel: Linux ARM 32-bit version 3.14.29

**Comment by arvvoid** [comment]
Its a device UUID encoding problem, some strange character in the device UUID.

Try the current master should fix the problem: https://github.com/arvvoid/plugin.video.hbogoeu/archive/master.zip

This will need some more testing before its released.

**Comment by mata007** [comment]
It works perfectly. Thank you

**Comment by arvvoid** [comment]
@allcontributors-bot please add @mata007 for bug
