### ISSUE TITLE
Operators that perform login redirection don't work

### ISSUE THREAD

**Issue by arvvoid** [arvvoid/plugin.video.hbogoeu#5]
* _Czech Republic: Skylink [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING]_
* _Czech Republic: UPC CZ [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING]_
* _Polonia: Cyfrowy Polsat [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING]_
* Romania: UPC Romania [REDIRECT LOGIN] **[ERROR NOT WORKING]**
* _Slovakia: Skylink [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING]_
* _Slovakia: UPC CZ [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING]_

* Romania: Telekom Romania (My Account) [REDIRECT LOGIN] [SOLVED CONFIRMED WORKING] 
(NOTE OTHER TELEKOM ROMANIA LOGIN OPTIONS HAVE BEEN ADDED TO HBO GO AND SHOULD WORK)

For a few operators, the login is not performed directly using the hbogo api. 
Instead, the user is redirected to the operator website the login is performed there, and then the operator login the user on hbogo and redirect back.
What exactly happens and how, will have to be figured out and then implemented in the add-on for those operators to work.

Impossible for me to fix and test since I don't have access to one of these operators. 
If someone using one of the listed above operators want to help fix the issue let me know here.

**Comment by Bibi40k** [comment]
Hi,
i login using Romania: Telekom Romania [REDIRECT LOGIN], how can i help ?

**Comment by arvvoid** [comment]
Hello, thanks for the help offer.
Please post a debug log with the latest version, make sure to try to play a video from the add on (https://kodi.wiki/view/Log_file/Easy).
That might be enough to fix it.

If not probably someone with access to one of these operators with programming skills will have to implement it and send a pull request.
The other option is, someone with access to one of these operators lands me an account for a couple of days so i can figure out the login and implement it. (please don't post login info publicly) But i will leave this option as last resort, let's start with debug logs.

It might be necessary to implement a different login procedure for each one of these operators, still not sure until i can see more details.

**Comment by arvvoid** [comment]
> (Yesterday, 13:45)kowalmisiek Wrote: 
> Does logging in to Poland / POLSAT already work in this version?
> 
> Unfortunately, it still does not work for Poland / POLSAT.
> 
> This is my kodi.log
> https://paste.kodi.tv/toxoqitafi.kodi

**Comment by arvvoid** [comment]
> fireangel 19.02.2019, 19:38 Kodi Forum
> I did another log file because the previuos log dont show anything , dont know why
> 
> log file  https://paste.kodi.tv/aqenukinoz

**Comment by arvvoid** [comment]
Found a useful implementation here: https://github.com/kszaq/plugin.video.hbogopl , need to be tested.  This might solve the problem for * UPC and * Cyfrowy Polsat and give hints to solve the rest as well.

**Comment by arvvoid** [comment]
Please test version: [plugin.video.hbogoeu-2.0.4~beta12.zip](https://github.com/arvvoid/repository.arvvoid/raw/master/plugin.video.hbogoeu/plugin.video.hbogoeu-2.0.4~beta12.zip) and report results with full debug log

**Comment by arvvoid** [comment]
Confirmed working for * Polonia: Cyfrowy Polsat [REDIRECT LOGIN].

Waiting for feedback for other providers. If no feedback for 2 weeks going to close this. Can be reopened if a problem is found.

**Comment by arvvoid** [comment]
> fireangel Wrote: 
> Hi.
> I instaled the lates plugin  v.2.0.5-beta16 , and after i log in with user and pasw i get  " HBO GO EU Error : check the log for more information " 
> Here are the log : [deqacawoka](https://paste.kodi.tv/deqacawoka) (paste)

confirmed still not working for UPC Romania

**Comment by cyberreality** [comment]
hi there !
i'm using Czech Republic: Skylink [REDIRECT LOGIN] and does not work, see my log: https://paste.kodi.tv/oviyezesiy.kodi
thanks

**Comment by alpa4r** [comment]
Hello,
Romania: UPC Romania does not work, how can i help?

**Comment by arvvoid** [comment]
Hello,
not having access to those operators is impossible for me to test and figure out the response given by the operator on successful login and extract the data necessary to complete the login procedure.
Found and implemented a working solution for Cyfrowy Polsat hoped it would be the same for the rest, and for the most part, it is, but there are some differences and some things have to be handled differently.
I have some ideas, will make a version that provides me a little more detail in debug log and hopefully that will help me solve the problem for the remaining 5 operators.

**Comment by cyberreality** [comment]
@arvvoid so please check my kodi log above, its for Skylink Czech, one can see it performs redirection to
OPERATOR REDIRECT: https://hbogo.skylink.cz/goauthenticate.aspx?client_id=HBO&redirect_uri=......
so maybe easy to fix

**Comment by arvvoid** [comment]
@cyberreality I checked your log. Read my answer above,  it's clear to me where and why it fails but I will have to extend what gets written to the debug log in hope of having enough info to fix it.
It's not a complicated fix, the complicated and slow part is getting the info necessary to fix it not having access to those operators. I have to write a slightly different login procedure for each one of those.

@alpa4r @cyberreality When I release the next beta version (probably next week) try again and send a debug log here. Hopefully will have enough info then to fix it.

CURRENT STATUS IS THIS:
- Czech Republic: Skylink [REDIRECT LOGIN] **[ERROR CONFIRMED STILL NOT WORKING]**
- Czech Republic: UPC CZ [REDIRECT LOGIN] **[ERROR CONFIRMED STILL NOT WORKING]**
- _Polonia: Cyfrowy Polsat [REDIRECT LOGIN] **[SOLVED CONFIRMED WORKING]**_
- Romania: Telekom Romania [REDIRECT LOGIN] [STATUS UNKOWN]
- Romania: UPC Romania [REDIRECT LOGIN] **[ERROR CONFIRMED STILL NOT WORKING]**
- Romania: Vodafone Romania 4GTV+ [REDIRECT LOGIN] [STATUS UNKOWN]
- Slovakia: Skylink [REDIRECT LOGIN] **[ERROR CONFIRMED STILL NOT WORKING]**
- Slovakia: UPC CZ [REDIRECT LOGIN] **[ERROR CONFIRMED STILL NOT WORKING]**

All other operators perform login directly on Hbo go and work fine.

@cyberreality Does a local CZ version of the add-on exist where Skylink Czech has already been figured out and implemented and works correctly?

**Comment by cyberreality** [comment]
> @cyberreality Does a local CZ version of the add-on exist where Skylink Czech has already been figured out and implemented and works correctly?

yope, there is a CZ version of HBOGO addon but only direct login works, no redirect at the moment ...
latest version attached:
[plugin.video.hbogocz-0.7.9a.zip](https://github.com/arvvoid/plugin.video.hbogoeu/files/3025767/plugin.video.hbogocz-0.7.9a.zip)

**Comment by TheImmortalOne** [comment]
For Romania - Telekom Romania, the redirect login is failing: http://paste.kodi.tv/cusiboluza

**Comment by arvvoid** [comment]
@TheImmortalOne tnx for the log, for now, I'm stuck with this, each of the operators with login redirect requires a slightly different implementation but not having access to those is difficult to test an figure out what has to be done. Ideally a local developer with access to the operator in question has to figure it out an implement it, and send a pull request.
Or someone has to provide me with all HTTP/S Requests and Responses sent between the Web browser and the Web server during the login procedure to the operator in question,

**Comment by TheImmortalOne** [comment]
@arvvoid, if you can link me a basic how-to for providing 'all the https requests and responses' (i suspect somehow from chrome's dev tools?), I can definitely help with that.

**Comment by ursan2003** [comment]
@arvvoid if you need the account hbo upc romania to try fix the login please leave a message
.Thanks

**Comment by chozze** [comment]
Let me know if you need access via UPC CZ. please help us :)

**Comment by arvvoid** [comment]
Atm i don't have the time too experiment with this, but will see what i can do when i have some free time if someone don't fix it before.

**Comment by arvvoid** [comment]
How to take a browser log from witch this have a chance to be figured out:

Use Chrome or Chromium

1) Logout from Hbo go if you are logged in
2) Go to your official Hbo go website and open Chrome developer tools

![Screenshot 2019-11-04 at 09 30 31](https://user-images.githubusercontent.com/46710439/68108052-fbaf1780-fee6-11e9-83bc-0de1eb28a097.png)

3) Open the Network TAB
4) Check the preserve log checkbox, perform the login

![Screenshot 2019-11-04 at 09 31 19](https://user-images.githubusercontent.com/46710439/68108051-fbaf1780-fee6-11e9-8613-4e896cb8a2de.png)

5) After you are successfully logged in save the log (right-clik on the list to show the context menu)

![Screenshot 2019-11-04 at 09 32 07](https://user-images.githubusercontent.com/46710439/68108050-fb168100-fee6-11e9-8360-66bc51d9d11c.png)

6) Your credentials can get exposed this way, change your password, al also you can manually open the log with your text editor and use the text replace function to replace your email and password with XXXX before sending.

7) You can post the log here if you cleaned it from your credentials if you prefer to send privately ask me for my email and i will give it to you, so you can send the log privately.

**Comment by rsn13** [comment]
>     1. Your credentials can get exposed this way, change your password, al also you can manually open the log with your text editor and use the text replace function to replace your email and password with XXXX before sending.

Here's my logs for the UPC Ro with blanked out credentials - no luck for ya snoopers xD hope this helps! :)
[hbogo.ro.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3806659/hbogo.ro.txt)

ps. I had 2 failed attempts first because I'm stupid and forgot which email I used

**Comment by arvvoid** [comment]
@rsn13 hello, thx that will be useful but will take some time. Please also send me a full debug log from Kodi take it while trying to setup the add-on

**Comment by durip** [comment]
hello, here is my logs for the Skylink Slovakia with blanked out credentials. thank you in advance
[hbogo.sk.har.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3848182/hbogo.sk.har.txt)
[kodi.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3848221/kodi.txt)

**Comment by xjoska** [comment]
Hi,

please find attached logs for UPC CZ.  Thank you.


[kodi2.log](https://github.com/arvvoid/plugin.video.hbogoeu/files/3884043/kodi2.log)
[hbogo.cz.har.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3884044/hbogo.cz.har.txt)

**Comment by ferdabasek** [comment]
Hello,
I tried to edit Skylink CZ.

So far it works for me. But you'll have to edit the code.

[constants.py.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3893908/constants.py.txt)
[handlereu.py.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3893909/handlereu.py.txt)

![obrazek](https://user-images.githubusercontent.com/58233539/69670260-cafc7100-1093-11ea-9eac-33445f1d9e37.png)

![obrazek](https://user-images.githubusercontent.com/58233539/69670372-0d25b280-1094-11ea-94e9-ecb05174e297.png)

**Comment by arvvoid** [comment]
@ferdabasek Hello, tnx for your contribution. Please send a pull request with your changes if you can.

**Comment by durip** [comment]
@ferdabasek great work! I tried your changes and it works for Skylink Slovakia.

**Comment by arvvoid** [comment]
@all-contributors please add @ferdabasek for ideas, code

**Comment by arvvoid** [comment]
@all-contributors please add @durip for userTesting

**Comment by arvvoid** [comment]
Hello Please test when you can @ferdabasek @durip : 
https://github.com/arvvoid/plugin.video.hbogoeu/archive/Skylink_fix.zip

Use install from zip function in Kodi

First, i need confirmation it works for Skylink CZ and SK on kodi 18

After that, if someone is willing will give instructions on how to test on Kodi 19 Python 3

After that, it can be merged and will be part of the next standard release.

REPORT RESULTS: https://github.com/arvvoid/plugin.video.hbogoeu/pull/78

**Comment by cyberreality** [comment]
if needed i can test on Kodi19/python3 ... i'd need help to start hbo go 
on python3, is there paralel build?

**Comment by arvvoid** [comment]
@cyberreality current Kodi master nightly builds can be used but only on MacOS or Linux (not sure about the Adndroid nightly build) that share the system python installation so pycryptodomex can be installed manually using pip. On windows Kodi 19 build pycrytodomex is currently broken so until that's fixed the add-on can't start on Kodi 19 Windows since pycryptodome is a prerequisite.

I suggest install on a test system or VM, Kodi 19 nightlies currently are nowhere near stable and should not be used except for testing.

**Comment by cyberreality** [comment]
yeah, because of pycrytodomex problem i'm running on kodi 19 from 
october 11th, lastone with python2
the only reason why runnin gon 19 is deinterlace problem on kodi18, so 
messy image on dvb-s2 ... so i'm somewhere i nthe middle :)

**Comment by arvvoid** [comment]
Fix for Sylink included in latest pre-release: https://github.com/arvvoid/plugin.video.hbogoeu/releases

**Comment by arvvoid** [comment]
Blind fix attempt for UPC CZ and SK if someone using UPC CZ from CZ or SK is reading please test and join discussion here:  https://github.com/arvvoid/plugin.video.hbogoeu/pull/79

@xjoska @chozze

**Comment by arvvoid** [comment]
https://github.com/arvvoid/plugin.video.hbogoeu/pull/79 provide a tentative fix for UPC Romania as well testers needed...

@alpa4r @ursan2003 @rsn13

**Comment by chozze** [comment]
@arvvoid I tried UPC CZ, same login error on Kodi 18

**Comment by ferdabasek** [comment]
@arvvoid 
I don't have UPC. UPC has probably different URLs for GET and POST.

[UPC_LOGIN.txt](https://github.com/arvvoid/plugin.video.hbogoeu/files/3906350/UPC_LOGIN.txt)

![obrazek](https://user-images.githubusercontent.com/58233539/69889222-1317cf80-12f0-11ea-8a23-f49fb8f6af1e.png)

**Comment by ferdabasek** [comment]
You may need to enter the complete URL:

> https://service.upc.cz/login/?TAM_OP=login&USERNAME=unauthenticated&ERROR_CODE=0x00000000&URL=%2Fsps%2FCZoauth20AA1%2Foauth20%2Fauthorize%3Fclient_id%3DZwB86MbT0Q14ggCatXG8%26redirect_uri%3Dhttps%253A%252F%252Fczapi.hbogo.eu%252Foauthupc%252Frequest3.aspx%26state%3DRsDqtLa4EetHF7i5jQmT8g%26scope%3Dcountry%253DCZ%25203rdparty%253DHBO%26response_type%3Dcode&REFERER=https%3A%2F%2Fhbogo.cz%2F&OLDSESSION=

**Comment by arvvoid** [comment]
@ferdabasek Might be, the only way to know is to try, so will update it now and we will see.

**Comment by arvvoid** [comment]
@ferdabasek not sure what is causing the problem, looking at the logs it should be fine posting simply to https://service.upc.cz/login/pkmslogin.form, should work looking at the browser logs... but can't really experiment not having access to the operator. That complete URL is just to reach the login page and is already called I think.

**Comment by splichy** [comment]
Hi @arvvoid you had wrong login redirect URL see https://github.com/arvvoid/plugin.video.hbogoeu/pull/84

**Comment by arvvoid** [comment]
@splichy tnx for your contribution, going to merge your PR

**Comment by arvvoid** [comment]
@all-contributors please add @splichy for ideas, code

**Comment by arvvoid** [comment]
Now just need confirmation this work for UPC CZ and SK: https://github.com/arvvoid/plugin.video.hbogoeu/archive/UPC_cz_sk_fix.zip
@xjoska @chozze @splichy

Also need confirmation if it works for UPC Romania: https://github.com/arvvoid/plugin.video.hbogoeu/archive/UPC_cz_sk_fix.zip
@alpa4r @ursan2003 @rsn13

Waiting on this to merge and push the next stable release

**Comment by chozze** [comment]
Bravo @arvvoid, I'm happy to confirm it works for UPC CZ!

**Comment by chozze** [comment]
btw just FYI, that UPC was bought by Vodafone so we can expect to change the login redirect URLs to change in near future once again.

**Comment by arvvoid** [comment]
@chozze Vodafone at least for other countries uses standard 3th party operator login. But changes can happen with no notice at any time in any segment. Hopefully, we will be able to sort out future changes quickly.

**Comment by splichy** [comment]
At least for UPC SK login will change after LGI finish transition(UPC SK wasn't part of deal).
Not sure what will happen with UPC CZ but there is chance that will remain unchanged as it uses upc.cz. domain.
We will see in a year

**Comment by splichy** [comment]
I have created pull request to add your addon into kodi-czsk repository
https://github.com/kodi-czsk/repository/pull/54

**Comment by arvvoid** [comment]
@splichy what version will be added there? pulling directly from master is not a good idea. I already maintain a repository with stable releases (https://github.com/arvvoid/repository.arvvoid) and plan to send the add-on to the official repo in the near future. So I would like to keep consistency with the versions in the repositories I would prefer to have only stable releases in repository.

I can create a branch for the czsk repository and keep there stable releases ready for release with no unnecessary additional files. Then the repository should pull releases from there, not from master if possible.

**Comment by arvvoid** [comment]
@splichy here you go clean branch stable release ready https://github.com/arvvoid/plugin.video.hbogoeu/tree/repo_ready_stable each stable release is a single commit will get updated with each stable release a stable release with this fixes will be available in max few days

**Comment by splichy** [comment]
kodi-czsk works on principe: when version in addon.xml changes in master than run: update submodule... and publish new version.
Especially for CZ & SK users this is one of the best sources of addons - it's much simpler to add just single repo than searching over internet and adding dozens repos 
IMHO it's good practice to keep development in branches and latest stable in master

right now kodi-czsk probably don't support updating from different branches
snippet from release.sh:
```#!/bin/bash
# taken grom xbmc-czech-sf.net
TOOLS=$(dirname "$0")"/tools"


BUILD_DIR=tmp
PUBLISH_DIR=repo
mkdir -p ${BUILD_DIR}

echo "Updating addon submodules"
git submodule init
git submodule update
git submodule foreach git pull origin master
```
see https://github.com/kodi-czsk/repository

**Comment by arvvoid** [comment]
@splichy the master branch is generally stable and functional but can contain files not really necessary to be included in the release zip (the add on will still work but unnecessary files, test scripts, github configurations, possibly build scripts, CI configs, gitignore lists ecc will get included as well)

**Comment by splichy** [comment]
according to release.sh precompiled, swap and hidden files are excluded:
```zip -FS -q -r "$package" "$dirname" -x "*.py[oc] *.sw[onp]" ".*"```
So prepending `.` before everything you don't wan't to be packed to final zip should be enough

**Comment by splichy** [comment]
^^^ sorry ```".*"``` is not part of -x argument
But I think that excludes in release script can be extended

**Comment by arvvoid** [comment]
@splichy if you want to include it in the CZ repo is fine, just some unneeded stuff will get in the ZIP with this system. After this release is ready (2.1.0), I will submit to the official Kodi repo.

**Comment by splichy** [comment]
OK, No problem, didn't know about your idea putting it into oficial repo

Dne út 10. 12. 2019 19:26 uživatel Arv.Void <notifications@github.com>
napsal:

**Comment by arvvoid** [comment]
Hello, we went a little offtopic with the last few posts, is there someone using UPC Romania able to test if by any chance the last PR fixed the login?
@alpa4r @ursan2003 @rsn13

test current master: https://github.com/arvvoid/plugin.video.hbogoeu/archive/master.zip

**Comment by cdps82** [comment]
Hi, could you please also check the login for Czech Republic/sledovanitv.cz s.r.o.? When I login, everything works just great, but only as long as I do the first restart of Kodi. Then I get a wrong credentials error message. What helps is to Log-out (settings reset) and then loging in over again. 

Thank you all for your great job!

PS: I can send you the credentials for testing purposes upon your request.

**Comment by arvvoid** [comment]
Hello @cdps82 tnx. 
What you describe is unrelated to this issue, that sounds more like a problem with your device/Kodi installation.
This issue is closed, not a proper place to bring new unrelated issues. Please open a proper issue following all the rules, with a proper full debug log otherwise I can't help you.
