### ISSUE TITLE
Missing features Spain/Nordic handler

### ISSUE THREAD

**Issue by arvvoid** [arvvoid/plugin.video.hbogoeu#69]
Some features are missing from the Spain/Nordic version My List, Add/Remove from my list, voting, search.

If someone is willing to log all these actions with chrome developer tools and post the log I can fix it (be informed that the log will probably contain your credentials so remove them before sending the log with a text editor search and replace function, and change your password after taking the log):

1) Go and login on Hbo website

![Screenshot 2019-11-04 at 09 30 31](https://user-images.githubusercontent.com/46710439/68108052-fbaf1780-fee6-11e9-83bc-0de1eb28a097.png)

2) Open the Developer Tools
3) Open the Network TAB
4) Check the preserve log checkbox, perform all these actions, and also play a video for few minutes so i have actions around playback logged as well.

5) After you performed all these actions save the log (right-clik on the list to show the context menu)

![Screenshot 2019-11-04 at 09 32 07](https://user-images.githubusercontent.com/46710439/68108050-fb168100-fee6-11e9-8360-66bc51d9d11c.png)

6) Open the log with a text editor replace all occurrences of your e-mail with XXX and replace all occurrences of your password with XXXXX using the search and replace function of your text editor. Save and send the log.

**Comment by arvvoid** [comment]
@Sakerdot @sanangel @PolliSoft @macardi @jhdgghost @jumakki

**Comment by macardi** [comment]
I have tried to do what you asked for but I may have done something wrong because the log file become extremely long and big (94 MB). To big to be uploaded here and to long to be pasted in pastebin or paste.ubuntu.

**Comment by arvvoid** [comment]
@macardi Hello tnx, keep in mind that all images ecc get logged as well, including the encrypted video segments during playback...
For now try to make a log without starting the playback perform all other action.
Then if you want can try to make one for playback as well but you need to start the playback and move quickly away from the playback page return to list because even if you stop the playback and remain on playback page the fragments will continue to download and get logged. Another option is to start playback and after 30 sec hit the red stop logging button and then save the log.

This way the log size should be manageable.

**Comment by jumakki** [comment]
Hi, I don't have active subscription at the moment, but I was still able to record search, adding to watchlist, showing watchlist and removing from watchlist. I hope those give you something to start with.
[REMOVED SOLVED]

**Comment by arvvoid** [comment]
@jumakki Thanks, from your log search and add and remove to watchlist is clear and can implement that easily now. But to get watchlist right I will need more stuff logged. The content id for watchlist is unique for each user so we need to catch the API call (on eu version is a config call that list all urls and content ids of special dirs). 

Can you log all that happens when hitting https://fi.hbonordic.com/watchlist from the start

**Comment by jumakki** [comment]
@arvvoid Here is logs from opening https://fi.hbonordic.com/watchlist right after opening Chrome.
[REMOVED SOLVED]

**Comment by arvvoid** [comment]
@jumakki Tnx, that's all the info I need. Soon search and watchlist will be implemented, then will need testers :) If you or someone can log the voting functions as well can add that too...

**Comment by arvvoid** [comment]
WORK IN PROGRESS: https://github.com/arvvoid/plugin.video.hbogoeu/pull/70

**Comment by arvvoid** [comment]
@jumakki @macardi Please test, this includes Search, My List, Add/Remove from my list, as always a full debug log would be helpful even if all seams to work.

[REMOVED BROKEN]

**Comment by macardi** [comment]
Hi, tested the new version. Search is working fine, Add/remove from my list gives me an error. 

[LOG REMOVED]

Thank you again for all your hard work with this plugin, love it!

**Comment by arvvoid** [comment]
@macardi Thank you for the feedback. Does listing My List work?

Here is a new test version: 
[BROKEN REMOVED]


This should fix the reported problems, let me know how it goes :)

**Comment by macardi** [comment]
Tested the new version. I can view my list, search is working, remove from my list is working. But add to my list gives an error message and the episode is not added to my list.

[LOG REMOVED]

**Comment by arvvoid** [comment]
@macardi Hello tnx, can you try to add to my list a movie and a series from the top folder not from Season or Episode listing

**Comment by macardi** [comment]
Ok, I think that I did what you asked for. The log became to big to be paste so providing a zip-file instead.

[LOG REMOVED]

**Comment by arvvoid** [comment]
@macardi Hello thank you. Please try this version 
[REMOVED SOLVED]

This version will also generate smaller logs

Try to add a movie and a series (by selecting the series, not an individual episode)

**Comment by macardi** [comment]
Hi, add a movie to my list works, and also add a tv series episode. But I got en error when trying to add a whole series. Adding a whole series is not possible in the official app or on the web 
either.

[REMOVED SOLVED]

**Comment by arvvoid** [comment]
@macardi @jumakki Ok tnx that work then. I assumed that it was the other way around because on the eu version you can add only a full series and no individual episode.

But does the whole series get added to my list after you add it from an individual episode or it add only that specific episode? (don't have access to the nordic/spain region so I work with no reference of the official client). Please describe what happens so I have a clear idea.

After I have a clear idea I can either leave the my list option only on items it will work on, or if the whole series is added, I can make it gather the first episode of the series and run add to my list on that. So if selected from the whole series it will still work that way.

Question 2, is there a voting system on the Nordic/Spain version? If yes I can implement that too but will need that logged in chrome.

**Comment by macardi** [comment]
The whole series does not get added to my list when I try to, I wish it would because just adding a single episode is pretty worthless. And there have been a lot of criticism about this behavior, but I guess you cant do anything about that because that how it is implemented by HBO Nordic. 

Concerning a voting system, I have checked in the app and in the browser  but cant find any. Unless I have missed something I guess its not available.

**Comment by arvvoid** [comment]
Thanks for the information. 
Yeah, that makes no sense at all, adding single episodes to watchlist is not useful at all IMO. Since is implemented like that on hbo side there is nothing to do. I will simply remove the add to my list option from directories it will appear only on movies and single episodes like in the official client.

Ok then that's it for now. I will close this issue since all the features I was planning to implement for now are done :)
