### ISSUE TITLE
Films are playing at low res and low fps despite CPU < 30% Raspberry pi 2 LibreElec

### ISSUE THREAD

**Issue by andreas1974** [arvvoid/plugin.video.hbogoeu#73]
* [X] Are you running the latest version?
Yes, plugin.video.hbogoeu-2.0.21.beta39

**Describe the bug**
Raspberry Pie 2. The movie plays smoothly but in low resolution (416x234 px) and 8 fps. All the CPU are at 30% or lower all the time. One of the CPU meters is often higher then the other three, at 20% or so, rare jumps up to 30%.

**To Reproduce**
Steps to reproduce the behaviour:
1. Play any film

**Expected behaviour**
I can't say I expected my Raspberry 2 to handle the playback very well, since it can't handle NetFlix in full resolution, but since the statistics show low numbers on the CPUs when playing the film from HBO, there may be room for improvements? Now there is low resolution **and** a low number of frames per second (8).

## Debug log

**Screenshots**
See screenshots attached for statistics and system description.

**Operating System**

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
LibreElec. See system attachments.
![DSCF3644](https://user-images.githubusercontent.com/998258/69095738-438b7e00-0a53-11ea-8f93-87f230d6f351.JPG)
![DSCF3649](https://user-images.githubusercontent.com/998258/69095736-438b7e00-0a53-11ea-8c51-58f544026ae8.JPG)
![DSCF3646](https://user-images.githubusercontent.com/998258/69095739-44241480-0a53-11ea-82e0-18a0868871b4.JPG)
![DSCF3647](https://user-images.githubusercontent.com/998258/69095740-44241480-0a53-11ea-91da-3f5adf7880e2.JPG)

**Additional context**
I'm not an experienced Raspberry or Linux user, so I'd like to excuse for reporting this at all... There may be some misunderstanding, or a setting that I need to change.

**Comment by arvvoid** [comment]
Hello, this doesn't sound right, that's not the usual behavior, with default inputstrea.adaptive settings and default Kodi settings if your network connection is ok, 1080p 25fps should work with no issues, and work with no issues on all my test devices including Rpi2 (but Rpi2 at the moment is really underpowered for a media center).
I have no vital information about the os used and/or your system configuration, other add-ons installed ecc... To get meaningful help providing a full debug log is recommended.
From the screenshot, I see you are using a pre-release version of LibreElec, tried with the current stable release of LibreElec?

Streams are Hardware decoded for Hbo Go CPU is not used for video decoding. With a recent widevine update, you might experience some stuttering at 1080p on Rpi2 but 720p should be fine in all cases, but with the last widevine update 1080p on Rpi2 should be fine again. Rpi3 has no issue on 1080p with Hbo go.

Your issue sounds more like an initial network speed estimate problem or inputstream.adaptive misconfiguration.

![50727530-76b76e00-111c-11e9-90a2-862dde869715](https://user-images.githubusercontent.com/46710439/69129075-fa1c4c80-0aad-11ea-8a22-7d10df20caf2.png)


In inputstream.adaptive settings try to force min bandwidth to 40000000 to exclude bandwidth estimation as a problem, you will need a stable bandwidth (internet speed) of at least 6mbps to play 1080p with no issues.
Also, make sure the Max resolution general decoder is set to Max.

_(If you want to limit Netflix add-on, and other widevine software decoded streams to a lower resolution) set Max resolution secure decoder to a lower value, recommended 420p limit for Rpi2, Rpi3+ 720p)_

Leave stream selection to **auto**.  IF it still doesn't work try to set stream selection to **manual** and try to select a higher stream manually.

Without a full debug log I can't help further,  instructions are in the project README.md.

**Comment by andreas1974** [comment]
You were perfectly right, it was a misconfiguration of inputstream.adaptive!
I guess it must have been when I tried to get Netflix to work last summer, that I changed Stream Selection to manual. Now I just set it to Auto, and the HBO series runs nicely at 25 fps and at the full resolution of my TV.
Thank you so much!
![I had stream selection set to manual](https://user-images.githubusercontent.com/998258/69135031-ba0e9700-0ab8-11ea-8ff3-c8511998addc.JPG)
_Setting "Stream selection" to Auto was the solution to the problem._
I don't know about the last two settings, whether I've changed them too (_Override DHCP status_ and _Ignore Display Resolution_ are _off_ in my setup), I notice they differ from the suggested settings above. But for the moment it seems to work fine anyway.

**Comment by arvvoid** [comment]
Glad its solved for you, enjoy the add-on :)

Ignore Display Resolution is useful on screens with no standard resolutions, if your screen is standard no need to enable that.
Override HDCP status is useful to report HDCP as enabled to the content provider, for this add-on it make no difference. For Netflix add-on, for example, is important if you are using it on a certified Widevine L1 device with HDCP support, because that way you can get 4k/1080p playback on all Netflix content, ofc only on a properly certified device (Android with L1).
Max. res general decoder is the max resolution used if hardware decoding is allowed (HBO go for example)
Max res secure decoder is the max allowed res when only software decoding is allowed (Netflix for example on non android l1 devices)

Closing this since its solved
